### PR TITLE
fix: [PL-25097]: temporarily disable 'savedProject' in PreferenceStore

### PR DESCRIPTION
**Pull request by mayankVermaHarness**
##### Summary:

Due to rare safety-check error that is thrown (as in PL-25097), the following 2 things are being done:
1. temporarily disable 'savedProject' in PreferenceStore & 
2. save 'projectsViewType' in machine scope

For context: The safety-check error is thrown only the first time when users lands on harness using a direct link or a bookmark url and is pre-logged-in.

##### Jira Links:

https://harness.atlassian.net/browse/PL-25097

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by mayankVermaHarness** [comment]
retrigger titlecheck

**Comment by mayankVermaHarness** [comment]
retrigger titlecheck

**Comment by mayankVermaHarness** [comment]
retrigger jest

**Comment by mayankVermaHarness** [comment]
retrigger jest

**Comment by mayankVermaHarness** [comment]
retrigger jest

**Comment by mayankVermaHarness** [comment]
retrigger jest

**Review by sunnykesh-harness — APPROVED** [review]

**Pull request merged**
