### PR TITLE
feat: [CDS-39322]: filePath and filePathRegex switching enhancements

### PR DESCRIPTION
**Pull request by chetanvekariya-harness**
### Summary
- Enhance the code which handles Value and Regex switching
- Write more test cases for the code which handles Value and Regex switching

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [x] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by chetanvekariya-harness** [comment]
retrigger titlecheck

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Comment by chetanvekariya-harness** [comment]
dockerize

**Review by bhavya-sinha — DISMISSED** [review]

**Review by vkbansal — APPROVED** [review]

**Comment by chetanvekariya-harness** [comment]
retrigger titlecheck

**Review by bhavya-sinha — APPROVED** [review]

**Review by vkbansal — APPROVED** [review]

**Review by bhavya-sinha — APPROVED** [review]

**Pull request merged**
