### PR TITLE
fix: [PL-24491]: Allow ReadOnly Vaults to be default SM

### PR DESCRIPTION
**Pull request by VikasMaddukuriHarness**
### Summary
Removed validation checks for a readOnly Vault to be used as default SM

Change summary - Added support for readOnly vaults to be default secret managers.

Test Summary:

create a new vault with both fields enabled and verified the same working in dB with all possible combinations (4 scenarios - none selected, default selected, readOnly selected, both selected)
modify existing vaults with the new UI and verified the correct boxes are getting checked in UI when we open an existing vault or after creating a new vault.
Updated the vault with all possible combination (4 scenarios - none selected, default selected, readOnly selected, both selected).
Verified the working of vaults (4 scenarios - none selected, default selected, readOnly selected, both selected)

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 30 Issues 
* Code issue 30 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11359)

**Comment by VikasMaddukuriHarness** [comment]
dockerize

**Review by meenakshi-harness — APPROVED** [review]

**Comment by VikasMaddukuriHarness** [comment]
trigger Cypress_Rest-Cypress_Rest

**Comment by VikasMaddukuriHarness** [comment]
trigger cypress

**Comment by VikasMaddukuriHarness** [comment]
trigger Cypress_CV, Cypress_Pipeline, Cypress_Rest

**Review by swarajcheguri-harness — APPROVED** [review]

**Pull request merged**
