### PR TITLE
fix: [CDS-433179]: Revert introducing formik into run pipeline form for Azure and expressions support for tags

### PR DESCRIPTION
**Pull request by vikrant-harness**
Reverts harness/harness-core-ui#11199

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 28 Issues 
* Code issue 28 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11302)

**Review by AshwinBhatkal-Harness — APPROVED** [review]

**Review by azharness — DISMISSED** [review]

**Comment by azharness** [comment]
retrigger titlecheck

**Review by azharness — APPROVED** [review]

**Comment by vikrant-harness** [comment]
retrigger coverage

**Comment by vikrant-harness** [comment]
retrigger jest

**Review by YounixIO — APPROVED** [review]

**Pull request merged**
