### PR TITLE
fix: [SRM-9294]: The number of nodes are going out of space and fix t…

### PR DESCRIPTION
**Pull request by vasuki-kalluri**
…he spacing in the Verify step summary section

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Review by shashidhargg — APPROVED** [review]

**Comment by vasuki-kalluri** [comment]
retrigger titlecheck

**Comment by vasuki-kalluri** [comment]
retrigger jest

**Comment by vasuki-kalluri** [comment]
trigger cypress

**Comment by vasuki-kalluri** [comment]
trigger cypress

**Pull request merged**
