### PR TITLE
fix: [CDB-390]: Dashboards - CG Deployment tags now show correctly

### PR DESCRIPTION
**Pull request by Harness-JKhattak**
### Summary

- Dashboards that were created with "Current Generation Deployment" tiles don't show a "Deployments" tag on them

#### Screenshots

| Before  | After |
| ------------- | ------------- |
| Screenshot 2022-09-23 at 15 53 27 | Screenshot 2022-09-23 at 17 26 51 |

_(See the Dashboards labelled with "CG" or "Current Generation" for ones with missing tags)_

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [X] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by Harness-JKhattak** [comment]
retrigger titlecheck

**Comment by Harness-JKhattak** [comment]
retrigger standards

**Review by crystal-fong — APPROVED** [review]

**Comment by Harness-JKhattak** [comment]
trigger cypress

**Comment by Harness-JKhattak** [comment]
trigger cypress

**Review by crystal-fong — APPROVED** [review]

**Review by willd0yle — APPROVED** [review]

**Pull request merged**
