### PR TITLE
fix: [CDS-43111]: Field Values persisting issue on store type change in manifests

### PR DESCRIPTION
**Pull request by vikrant-harness**
### Summary

Previous Values for Manifests still persists on changing the store type , the reset function was only called on changing the manifest type but was not present for store type. This was present in studio view , service overrides and K8s Apply Step

#### Screenshots

https://user-images.githubusercontent.com/106532291/189992380-81b4ea66-417e-4159-8544-aaa6893c770d.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by vikrant-harness** [comment]
trigger cypress

**Comment by vikrant-harness** [comment]
trigger cypress

**Comment by vikrant-harness** [comment]
trigger cypress

**Comment by vikrant-harness** [comment]
trigger cypress

**Comment by vikrant-harness** [comment]
trigger cypress

**Comment by vikrant-harness** [comment]
trigger cypress

**Review by YounixIO — APPROVED** [review]

**Pull request merged**
