### PR TITLE
feat: [CDS-38535]: Remote Backend configuration for Terraform Plan and Apply

### PR DESCRIPTION
**Pull request by Tamaraius**
### Summary

Remote Backend Configuration is added as an option in addition to Inline Backend Configuration that was previously present
for Terraform Plan and Apply, not Terraform Destroy

Remote Backend Configuration is mostly the same as Remote Configuration so most of the logic is reused/adapted so it can serve both, Remote BC in addition has Harness File Store as an option

#### Screenshots

https://user-images.githubusercontent.com/96610348/196396678-3db04d2a-8adb-489a-b12e-4b6461d3cbee.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

## [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 188 Issues 
* Code issue 188 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11049)

**Comment by Tamaraius** [comment]
retrigger coverage

**Comment by Tamaraius** [comment]
retrigger coverage

**Review by chetanvekariya-harness — APPROVED** [review]

**Review by azharness — APPROVED** [review]

**Comment by Tamaraius** [comment]
retrigger jest

**Comment by Tamaraius** [comment]
retrigger coverage

**Comment by Tamaraius** [comment]
retrigger typecheck

**Comment by Tamaraius** [comment]
retrigger jest

**Review by chetanvekariya-harness — APPROVED** [review]

**Review by YounixIO — APPROVED** [review]

**Pull request merged**
