### PR TITLE
feat: [PIE-3871]: Resource Constraint - Execution View

### PR DESCRIPTION
**Pull request by ishantmehtaharness**
##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by ishantmehtaharness** [comment]
dockerize

**Comment by ishantmehtaharness** [comment]
trigger cypress

**Review by satyam-harness — APPROVED** [review]

**Review by devinder-harness — APPROVED** [review]

**Comment by ishantmehtaharness** [comment]
trigger rebase

**Comment by ishantmehtaharness** [comment]
merged here
https://github.com/harness/harness-core-ui/pull/9660/files

**Pull request closed without merging**
