### PR TITLE
fix: [CCM-8510]: changed table column header for savings tab in commitment orchestration

### PR DESCRIPTION
**Pull request by rishik30**
#### Screenshots

| **Before** | **After** |
| :-: | :-: |
| Screenshot 2022-09-02 at 3 56 50 PM | Screenshot 2022-09-02 at 3 53 36 PM | 

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

## [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

### CODE REVIEW

**Comment by rishik30** [comment]
retrigger titlecheck

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Code issue 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10968)

**Comment by rishik30** [comment]
retrigger jest

**Comment by rishik30** [comment]
trigger cypress

**Review by rajarshee-harness — APPROVED** [review]

**Review by jyotiarora-harness — APPROVED** [review]

**Pull request merged**
