### PR TITLE
fix: [CDS-37178]: reference by support for templates

### PR DESCRIPTION
**Pull request by samarth-sharma31**
##### Summary:

Reference by support will enable to see usages of a particular template in other pipelines and nested templates

##### Screenshots:

https://user-images.githubusercontent.com/96409598/170143750-4e3864bb-eb67-4f49-8104-6bd57bb6afda.mov

Screenshot 2022-05-25 at 4 11 47 AM
Screenshot 2022-05-25 at 4 11 57 AM
Screenshot 2022-05-25 at 4 12 11 AM

Screenshot 2022-06-07 at 1 19 10 AM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by samarth-sharma31** [comment]
retrigger titlecheck

**Comment by samarth-sharma31** [comment]
retrigger jest

**Comment by samarth-sharma31** [comment]
dockerize

**Comment by samarth-sharma31** [comment]
retrigger jest

**Comment by samarth-sharma31** [comment]
dockerize

**Comment by samarth-sharma31** [comment]
trigger cypress

**Comment by samarth-sharma31** [comment]
retrigger jest

**Comment by samarth-sharma31** [comment]
dockerize

**Comment by samarth-sharma31** [comment]
dockerize

**Comment by samarth-sharma31** [comment]
dockerize

**Comment by samarth-sharma31** [comment]
retrigger build

**Comment by samarth-sharma31** [comment]
dockerize

**Comment by samarth-sharma31** [comment]
dockerize

**Review by yc147 — DISMISSED** [review]

**Review by yc147 — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Review by devinder-harness — APPROVED** [review]

**Pull request merged**
