### PR TITLE
fix: [CI-7335]: deprecated image empty object check

### PR DESCRIPTION
**Pull request by shaurya-harness**
### Summary

deprecated image empty object check added, otherwise deprecated image banner is showing even when there are no deprecated images

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by YounixIO — APPROVED** [review]

**Review by kapilkumawat86 — DISMISSED** [review]

**Review by YounixIO — COMMENTED** [review]
@shaurya-harness: the falsy check and isEmpty check would check for the same thing right ??

**Comment by shaurya-harness** [comment]
> @shaurya-harness: the falsy check and isEmpty check would check for the same thing right ??

@YounixIO falsy checks for null or undefined, isEmpty checks for empty object

**Comment by YounixIO** [comment]
@shaurya-harness : Then only isEmpty should be good enough.

**Review by d1wilko — DISMISSED** [review]
LGTM

**Comment by YounixIO** [comment]
Screenshot 2023-03-08 at 6 35 52 PM

**Review by YounixIO — DISMISSED** [review]

**Comment by shaurya-harness** [comment]
> @shaurya-harness : Then only isEmpty should be good enough.

@YounixIO right, updated

**Review by YounixIO — APPROVED** [review]

**Review by d1wilko — APPROVED** [review]
LGTM

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
