### PR TITLE
feat: [PIE-3226]: added coverage for files under GitOps

### PR DESCRIPTION
**Pull request by Sagar-Rajput7**
##### Summary:

Added Coverage improvement for files under GitOps

##### Jira Links:

https://harness.atlassian.net/browse/PIE-3226

##### Screenshots:

Earlier :

Screenshot 2022-03-25 at 10 15 58 AM

Now:

Screenshot 2022-03-25 at 10 22 26 AM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by Sagar-Rajput7** [comment]
retrigger jest

**Comment by Sagar-Rajput7** [comment]
retrigger titlecheck

**Comment by Sagar-Rajput7** [comment]
trigger cypress

**Comment by Sagar-Rajput7** [comment]
retrigger jest

**Review by kapilkumawat86 — APPROVED** [review]

**Review by vkbansal — APPROVED** [review]

**Pull request merged**
