### PR TITLE
feat: [PL-38974]: Allow deletion of SCIM users with a warning

### PR DESCRIPTION
**Pull request by tiwaritejas**
### Summary

We will now allow deletion of SCIM users with a warning.

#### Screenshots

https://github.com/harness/harness-core-ui/assets/97941439/c22d96d9-94b0-4cb9-807c-21719c711b93

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by avinashmadhwani02 — APPROVED** [review]

**Review by mayankVermaHarness — APPROVED** [review]

**Comment by tiwaritejas** [comment]
retrigger jest

**Comment by tiwaritejas** [comment]
retrigger cypress-cv

**Comment by tiwaritejas** [comment]
retrigger jest

**Comment by tiwaritejas** [comment]
retrigger coverage

**Pull request merged**
