### PR TITLE
fix: [CCM-12311]: remove saved/applied filters when url is changed

### PR DESCRIPTION
**Pull request by rishik30**
### Summary

In AutoStopping list page, when a filter is selected, it gets appended to the url which makes the url shareable. Now if someone clears on the list page nav link then the filter params in the url is removed and content is loaded accordingly but the filter UI still shows the previous applied filter.
This PR solves the above mentioned problem by clearing out the filter on navigation change.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by rishik30** [comment]
retrigger coverage

**Comment by rishik30** [comment]
retrigger titlecheck

**Comment by rishik30** [comment]
retrigger cypress-cd

**Comment by rishik30** [comment]
retrigger cypress-pipeline

**Comment by rishik30** [comment]
retrigger cypress-rest

**Review by jyotiarora-harness — APPROVED** [review]

**Pull request merged**
