### PR TITLE
feat: [CDB-783]: Dashboards - Added SRM Module support

### PR DESCRIPTION
**Pull request by Harness-JKhattak**
### Summary

- SRM has been added to the Dashboards Module
- "Service Reliability" tag added to module filter bar and dashboard cards

#### Screenshots

Screenshot 2023-03-30 at 11 47 22

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by Harness-JKhattak** [comment]
retrigger typecheck

**Comment by Harness-JKhattak** [comment]
retrigger typecheck

**Comment by Harness-JKhattak** [comment]
retrigger titlecheck

**Review by sean-harness — APPROVED** [review]

**Review by willd0yle — APPROVED** [review]

**Comment by Harness-JKhattak** [comment]
retrigger cypress-pipeline

**Comment by Harness-JKhattak** [comment]
retrigger cypress-cv

**Comment by Harness-JKhattak** [comment]
retrigger cypress-cd

**Review by sean-harness — APPROVED** [review]

**Pull request merged**
