### PR TITLE
fix: [DEL-3583]: Changed text from YAML to YML

### PR DESCRIPTION
**Pull request by amitsh14**
##### Summary:

Changed the text from YAML to YML at two places:
1: Delegate setup text
2: Review step title in the tracker 

##### Jira Links:

https://harness.atlassian.net/browse/DEL-3583

##### Screenshots:
image (1)

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by amitsh14** [comment]
Updated the PR title

**Comment by amitsh14** [comment]
retrigger titlecheck

**Comment by amitsh14** [comment]
trigger rebase

**Comment by amitsh14** [comment]
retrigger titlecheck

**Comment by amitsh14** [comment]
retrigger titlecheck

**Comment by deepesh-ui** [comment]
trigger cypress

**Review by deepesh-ui — APPROVED** [review]

**Review by azharness — APPROVED** [review]

**Pull request merged**
