### PR TITLE
feat: [PIE-3302]: Rest zoom on change of stage change selection

### PR DESCRIPTION
**Pull request by kapilkumawat86**
##### Screenshots:

image

image

https://user-images.githubusercontent.com/57665511/160767405-6361a51d-fa19-4928-ab05-0d575ff2337f.mov

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by kapilkumawat86** [comment]
dockerize

**Review by ishantmehtaharness — APPROVED** [review]
Looks Good

**Comment by kapilkumawat86** [comment]
dockerize

**Comment by kapilkumawat86** [comment]
trigger rebase

**Review by yc147 — APPROVED** [review]

**Review by vkbansal — APPROVED** [review]

**Review by chiragp1212 — APPROVED** [review]

**Pull request merged**
