### PR TITLE
feat: [SRM-9295]: Adding plumbling to report ErrorAnalysisSummary data…

### PR DESCRIPTION
**Pull request by ccaspanello**
… from the backend

##### Summary:

Adding plumbling to report ErrorAnalysisSummary data from the backend

##### Jira Links:

https://harness.atlassian.net/browse/SRM-9295

##### Screenshots:

image

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by ccaspanello** [comment]
retrigger titlecheck

**Comment by ccaspanello** [comment]
retrigger titlecheck

**Comment by ccaspanello** [comment]
retrigger titlecheck

**Comment by ccaspanello** [comment]
retrigger titlecheck

**Comment by ccaspanello** [comment]
retrigger eslint

**Review by tan-nhu — APPROVED** [review]

**Comment by ccaspanello** [comment]
trigger cypress

**Comment by ccaspanello** [comment]
retrigger typecheck

**Review by anjanBalgovind — DISMISSED** [review]

**Review by DFieldFL — APPROVED** [review]

**Comment by ccaspanello** [comment]
retrigger coverage

**Review by anjanBalgovind — APPROVED** [review]

**Pull request merged**
