### PR TITLE
feat: [SSCA-294]: Add ingestion support to CI's SSCA Orchestration Step

### PR DESCRIPTION
**Pull request by williamwissemann**
### Summary

SSCA Step: 
Introduce a new input at the top of the SSCA Orchestration step: "SBOM Method” with two inputs- Generation, Ingestion
- When Generation is selected, our flow remains the same
- When Ingestion is selected then we take the path to the SBOM file. To begin with, SBOM file path can support the 
- Change label to “SBOM FIle” -> “SBOM File Path.”

STO BDH Step:
- Change label from “SBOM Generation” to “Generate SBOM”

#### Screenshots

Screenshot 2023-08-17 at 12 31 57 PM

Screenshot 2023-08-17 at 12 33 01 PM

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by r0610205 — APPROVED** [review]

**Comment by williamwissemann** [comment]
retrigger sonar

**Review by udayvunnam — APPROVED** [review]

**Comment by williamwissemann** [comment]
retrigger cypress-cd

**Comment by williamwissemann** [comment]
retrigger cypress-pipeline

**Comment by williamwissemann** [comment]
retrigger cypress-cv

**Comment by williamwissemann** [comment]
retrigger cypress-cd

**Comment by williamwissemann** [comment]
retrigger cypress-pipeline

**Pull request merged**
