### PR TITLE
feat: [PIE-2600]: Pipeline Studio diagram

### PR DESCRIPTION
**Pull request by satyam-harness**
##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by devinder-harness** [comment]
res

**Comment by satyam-harness** [comment]
retrigger build

**Comment by satyam-harness** [comment]
retrigger typecheck

**Comment by satyam-harness** [comment]
retrigger typecheck

**Comment by satyam-harness** [comment]
dockerize

**Comment by satyam-harness** [comment]
dockerize

**Comment by satyam-harness** [comment]
dockerize

**Comment by satyam-harness** [comment]
dockerize

**Comment by satyam-harness** [comment]
dockerize

**Comment by satyam-harness** [comment]
dockerize

**Comment by satyam-harness** [comment]
dockerize

**Comment by satyam-harness** [comment]
dockerize

**Pull request closed without merging**
