### PR TITLE
feat: [CDS-43251]: add connectivity step for Azure, Artifactory, GCP, AWS, Docker

### PR DESCRIPTION
**Pull request by Tamaraius**
### Summary

Added a missing Connectivity step when creating a new Connector via + New Connector button for Azure, Artifactory, GCP, AWS and Docker connectors

#### Screenshots

https://user-images.githubusercontent.com/96610348/190980219-2c85102e-63a0-48f0-90b1-d1c94d88ac87.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 32 Issues 
* Code issue 32 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11303)

**Comment by Tamaraius** [comment]
retrigger coverage

**Comment by Tamaraius** [comment]
retrigger titlecheck

**Comment by Tamaraius** [comment]
retrigger titlecheck

**Review by satyam-harness — DISMISSED** [review]

**Review by willd0yle — APPROVED** [review]

**Review by chetanvekariya-harness — APPROVED** [review]

**Review by willd0yle — DISMISSED** [review]

**Comment by Tamaraius** [comment]
retrigger coverage

**Comment by Tamaraius** [comment]
retrigger jest

**Comment by YounixIO** [comment]
retrigger coverage

**Review by willd0yle — APPROVED** [review]

**Review by YounixIO — APPROVED** [review]

**Pull request merged**
