### PR TITLE
feat: [CET-1193] Add Monitored Services list to CET

### PR DESCRIPTION
**Pull request by ricksjames**
### Summary

Add a new monitored services page to the Continuous Error tracking module.

#### Screenshots

Screen Shot 2023-04-04 at 2 23 26 PM
Screen Shot 2023-04-04 at 2 23 50 PM

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by ricksjames** [comment]
retrigger jest

**Comment by ricksjames** [comment]
retrigger jest coverage

**Comment by ricksjames** [comment]
retrigger jest

**Comment by ricksjames** [comment]
retrigger coverage

**Review by abeg777 — APPROVED** [review]

**Review by tan-nhu — APPROVED** [review]

**Review by abeg777 — APPROVED** [review]

**Review by angelo-m-rodriguez — APPROVED** [review]

**Pull request merged**
