### PR TITLE
feat: [CDS-71334]: implement ServerlessAwsLambdaPackageV2 step

### PR DESCRIPTION
**Pull request by chetanvekariya-harness**
### Summary
- Implement edit and runtime view changes for the step
- Add validation for connectorRef field in runtime view for Serverless 2.0 steps
- Convert labels, annotations and nodeSelector to object before sending to BE

#### Screenshots
Screenshot 2023-06-21 at 4 51 14 PM

Screenshot 2023-06-21 at 4 51 33 PM

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by chetanvekariya-harness** [comment]
retrigger cypress-pipeline

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Review by ishantmehtaharness — APPROVED** [review]
Looks Good Chetan

**Review by Sagar-Rajput7 — APPROVED** [review]

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Comment by chetanvekariya-harness** [comment]
retrigger cypress-cv

**Review by ishantmehtaharness — APPROVED** [review]
looks good to me

**Review by Sagar-Rajput7 — APPROVED** [review]

**Review by vikrant-harness — APPROVED** [review]

**Pull request merged**
