### PR TITLE
fix: [PIE-5434]: Fix redirect url when cloning pipeline

### PR DESCRIPTION
**Pull request by depanshu-dhiman**
### Summary
After pipeline was clone successfully, the redirect url didn't contain necessary store metadata due to which we got the error that pipeline doesn't exist.
REMOTE pipelines are dependent on these extra query params.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 1 Issues 
* Code issue 1 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11425)

**Comment by depanshu-dhiman** [comment]
retrigger titlecheck

**Comment by depanshu-dhiman** [comment]
retrigger jest

**Review by vkbansal-harness — APPROVED** [review]

**Comment by depanshu-dhiman** [comment]
retrigger jest

**Comment by depanshu-dhiman** [comment]
retrigger jest

**Review by Sagar-Rajput7 — APPROVED** [review]

**Pull request merged**
