### PR TITLE
fix: [PL-24878]: changed value of timePSTLabel

### PR DESCRIPTION
**Pull request by mitishapandey**
##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by mitishapandey** [comment]
retrigger titlecheck

**Comment by mitishapandey** [comment]
retrigger titlecheck

**Comment by mitishapandey** [comment]
trigger rebase

**Comment by mitishapandey** [comment]
trigger cypress

**Review by swarajcheguri-harness — APPROVED** [review]

**Review by avinashmadhwani02 — APPROVED** [review]

**Pull request merged**
