### PR TITLE
fix: [FFM-2204]: Restricting the Avatar Group to prevent overflow in container

### PR DESCRIPTION
**Pull request by laura-mannus**
… large amounts.

##### Summary:

There was no restriction on the avatar group on the 'Custom Rules' section of the Targeting in FF. Adding this prevents the overflow of large quantities of targets as shown in the bug.

##### Screenshots:

image

image

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Review by crystal-fong — DISMISSED** [review]
beautiful

**Comment by laura-mannus** [comment]
retrigger titlecheck

**Review by chrisblakely01 — APPROVED** [review]

**Comment by chrisblakely01** [comment]
trigger cypress

**Comment by laura-mannus** [comment]
retrigger cypress

**Comment by laura-mannus** [comment]
trigger cypress

**Review by knagurski — APPROVED** [review]
Nice and simple 👍🏻

**Review by crystal-fong — APPROVED** [review]

**Review by chrisblakely01 — APPROVED** [review]

**Pull request merged**
