### PR TITLE
feat: [PL-41640]:Update config.yaml to set API_URL to /gateway

### PR DESCRIPTION
**Pull request by piyush-harness**
### Summary

We need to set API URL for next-gen-ui to consider host value from browser url and use /gateway only as API URL which is relative URL from where UI is loaded.This is required to make UI work with global gateway URLs.

Tested in Devspaces.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by piyush-harness** [comment]
retrigger titlecheck

**Comment by piyush-harness** [comment]
trigger titlecheck

**Comment by piyush-harness** [comment]
trigger Title_Check

**Comment by piyush-harness** [comment]
retrigger titlecheck

**Comment by piyush-harness** [comment]
retrigger titlecheck

**Review by abhinavrastogi-harness — APPROVED** [review]

**Review by saitejavn-harness — APPROVED** [review]

**Pull request merged**
