### PR TITLE
fix: [STO-5177]: fix for Security step template with input variables

### PR DESCRIPTION
**Pull request by r0610205**
### Summary

Fixes rendering of Security step in the template mode

#### Screenshots

Screen Shot 2022-12-23 at 1 27 12 PM
Screen Shot 2022-12-23 at 1 27 22 PM

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by r0610205** [comment]
retrigger titlecheck

**Comment by r0610205** [comment]
retrigger titlecheck

**Comment by r0610205** [comment]
retrigger jest

**Comment by r0610205** [comment]
retrigger jest

**Comment by r0610205** [comment]
retrigger coverage

**Review by atmollo-harness — APPROVED** [review]

**Review by ahokinson — APPROVED** [review]

**Pull request merged**
