### PR TITLE
fix: [CCM-5409]: show AWS connector errors in UI

### PR DESCRIPTION
**Pull request by rajarshee-harness**
##### Jira Links:

https://harness.atlassian.net/browse/CCM-5409

##### Screenshots:

Screenshot 2022-03-24 at 6 02 02 PM
Screenshot 2022-03-24 at 5 50 38 PM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by jenil-harness** [comment]
trigger cypress

**Comment by rajarshee-harness** [comment]
trigger cypress

**Comment by rajarshee-harness** [comment]
retrigger titlecheck

**Comment by rajarshee-harness** [comment]
trigger cypress

**Pull request closed without merging**
