### PR TITLE
feat: [CI-5545]: front end changes for mac cloud

### PR DESCRIPTION
**Pull request by d1wilko**
### Summary

Add Mac OS and ARM64 arch options to cloud infra

#### Screenshots

image

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by d1wilko** [comment]
retrigger titlecheck

**Comment by d1wilko** [comment]
retrigger cypress-cd

**Comment by d1wilko** [comment]
retrigger titlecheck

**Review by vardanbansal-harness — DISMISSED** [review]

**Review by shaurya-harness — DISMISSED** [review]

**Review by abhinavrastogi-harness — DISMISSED** [review]

**Review by tan-nhu — DISMISSED** [review]

**Review by vardanbansal-harness — DISMISSED** [review]

**Comment by d1wilko** [comment]
retrigger cypress-rest

**Comment by d1wilko** [comment]
retrigger typecheck

**Review by shaurya-harness — DISMISSED** [review]

**Pull request closed without merging**
