### PR TITLE
fix: [CDS-39162]: Support for template schema validation behind featu…

### PR DESCRIPTION
**Pull request by samarth-sharma31**
…re flag

##### Summary:

Adds support for template yaml schema validation - behind a FF -> TEMPLATE_SCHEMA_VALIDATION

##### Jira Links:

https://harness.atlassian.net/browse/CDS-39162

##### Screenshots:

https://user-images.githubusercontent.com/96409598/175520819-c35445f7-0fb5-4853-944c-f2b523c69b85.mov

https://user-images.githubusercontent.com/96409598/176306854-fba1495b-054f-4b83-a0ec-0573a2be58c5.mov

https://user-images.githubusercontent.com/96409598/176306917-d8bc0607-7339-4971-afb6-f79355e1de30.mov

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by samarth-sharma31** [comment]
dockerize

**Comment by samarth-sharma31** [comment]
dockerize

**Comment by samarth-sharma31** [comment]
dockerize

**Comment by samarth-sharma31** [comment]
dockerize

**Comment by samarth-sharma31** [comment]
retrigger jest

**Review by AshwinBhatkal-Harness — APPROVED** [review]

**Review by yc147 — APPROVED** [review]

**Pull request merged**
