### PR TITLE
feat: [SRM-11377]: Added Code Errors Page to SRM, FF added SRM_ET_EXPERIMENTAL

### PR DESCRIPTION
**Pull request by abeg777**
### Summary

Added Code Errors page and navigation tab to SRM. Integrated ET UI event list microfrontend component on new page. Applied fix for local dev env config. Added feature flag for new page (disabled for now).

#### Screenshots
Before:
image

After:
image

### CODE REVIEW

**Comment by abeg777** [comment]
trigger rebase

**Comment by abeg777** [comment]
retrigger titlecheck

**Comment by abeg777** [comment]
retrigger titlecheck

**Review by vkbansal-harness — APPROVED** [review]

**Comment by abeg777** [comment]
retrigger coverage

**Comment by abeg777** [comment]
trigger cypress

**Comment by abeg777** [comment]
trigger rebase

**Comment by abeg777** [comment]
retrigger coverage

**Comment by abeg777** [comment]
trigger rebase

**Comment by abeg777** [comment]
retrigger coverage

**Comment by abeg777** [comment]
trigger rebase

**Comment by abeg777** [comment]
trigger cypress

**Pull request merged**
