### PR TITLE
feat: [FFM-1783]: Targeting rules tab - Add/remove variations, add/remove targets/target groups to variations

### PR DESCRIPTION
**Pull request by chrisblakely01**
##### Summary:

This PR allows the use to add targeting rules for a given variation. **NOTE: See video below for context. This feature is hidden behind a flag and not user facing yet**

IN SCOPE

- Add/Remove a new variation
- Add/Remove targets from a variation
- Add/Remove target groups from a variation 
- Save changes via API call

NOT IN SCOPE

- Percentage rollout
- Default off variation
- Anything else not mentioned above

##### Jira Links:

https://harness.atlassian.net/browse/FFM-1513

##### Coverage

Screenshot 2022-03-15 at 10 46 32

##### Video:

https://user-images.githubusercontent.com/10871707/158361283-9f4677cf-0722-4697-b093-1480b07aa687.mov

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by chrisblakely01** [comment]
retrigger titlecheck

**Comment by chrisblakely01** [comment]
retrigger titlecheck

**Comment by chrisblakely01** [comment]
retrigger typecheck

**Review by crystal-fong — APPROVED** [review]
looks good. Just a question, what happens if users assigns `True` and `False` to the same target / target group?

**Comment by chrisblakely01** [comment]
> looks good. Just a question, what happens if users assigns `True` and `False` to the same target / target group?

Good Q - its handled on the backend, most recently added rule wins, and the other is ignored/deleted

**Review by willd0yle — CHANGES_REQUESTED** [review]
NICE!

**Review by willd0yle — APPROVED** [review]

**Pull request merged**
