### PR TITLE
feat: [GTM-947]: add groupId to page event

### PR DESCRIPTION
**Pull request by nanaxuHarness**
##### Summary:

this is to formalize adding user id properties into telemetry fwk

##### Jira Links:

https://harness.atlassian.net/browse/PLG-947

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by nanaxuHarness** [comment]
retrigger typecheck

**Comment by nanaxuHarness** [comment]
retrigger typecheck

**Review by pranil-harness — APPROVED** [review]

**Review by knagurski — DISMISSED** [review]
Nice and simple, just like myself

**Review by crystal-fong — DISMISSED** [review]

**Comment by nanaxuHarness** [comment]
> Nice and simple, just like myself

+totally agreed!

**Review by Harness-JKhattak — DISMISSED** [review]
Looks good! :shipit:

**Comment by nanaxuHarness** [comment]
trigger cypress

**Comment by nanaxuHarness** [comment]
trigger cypress

**Comment by nanaxuHarness** [comment]
trigger cypress

**Comment by nanaxuHarness** [comment]
retrigger jest

**Comment by nanaxuHarness** [comment]
trigger cypress

**Comment by nanaxuHarness** [comment]
trigger cypress

**Review by tan-nhu — APPROVED** [review]

**Pull request merged**
