### PR TITLE
fix: [CI-5315]: configure connector trigger error

### PR DESCRIPTION
**Pull request by mtran7**
#### Screenshots
image

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

## [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

### CODE REVIEW

**Comment by mtran7** [comment]
retrigger titlecheck

**Comment by mtran7** [comment]
retrigger jest

**Review by tan-nhu — APPROVED** [review]

**Comment by mtran7** [comment]
retrigger sonar

**Review by vardanbansal-harness — APPROVED** [review]

**Review by d1wilko — APPROVED** [review]

**Comment by mtran7** [comment]
image

Sonar issue

**Pull request merged**
