### PR TITLE
fix: [PLG-2124]: Updated module names

### PR DESCRIPTION
**Pull request by devinder-harness**
### Summary
Updated Module names in Release Notes Table

https://harness.atlassian.net/browse/PLG-2123

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by neelam-harness — APPROVED** [review]
LGTM.
Could you also add screenshots from the local build in the description ? Easier to map it for the reader. Thanks

**Comment by devinder-harness** [comment]
retrigger titlecheck

**Review by dhruvUpadhyay07 — DISMISSED** [review]

**Comment by devinder-harness** [comment]
retrigger titlecheckl

**Review by dhruvUpadhyay07 — DISMISSED** [review]

**Review by bhavya-sinha — APPROVED** [review]

**Review by sonaligoyal-harness — APPROVED** [review]

**Review by dhruvUpadhyay07 — APPROVED** [review]

**Review by bhavya-sinha — APPROVED** [review]

**Review by neelam-harness — COMMENTED** [review]
LGTM

**Pull request merged**
