### PR TITLE
fix: [CDS-42707]: update to step which is part of rollbackSteps fixed

### PR DESCRIPTION
**Pull request by chetanvekariya-harness**
### Summary

JIRAs that should get addressed with this change - 
https://harness.atlassian.net/browse/CDS-42707
https://harness.atlassian.net/browse/CDS-41814
https://harness.atlassian.net/browse/CDS-42849

- Also, fixed flaky jest test cases related to ECS Infra.

#### Screenshots
https://user-images.githubusercontent.com/81295223/188634448-35fb8546-76f2-4980-804d-c69690922efc.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

## [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11060)

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Review by PratyushGar — APPROVED** [review]

**Comment by chetanvekariya-harness** [comment]
retrigger coverage

**Review by satyam-harness — APPROVED** [review]

**Pull request merged**
