### PR TITLE
fix: [CDS-79823]: Fix onboarding flow when FF is enabled

### PR DESCRIPTION
**Pull request by MondalSayantan**
### Summary

Fix onboarding flow when CDS_NAV_2_0 is enabled

#### Screenshots

https://github.com/harness/harness-core-ui/assets/62999423/bbe30726-3403-4e2e-bd89-2b632ece624d

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by MondalSayantan** [comment]
retrigger titlecheck

**Comment by MondalSayantan** [comment]
retrigger titlecheck

**Comment by MondalSayantan** [comment]
retrigger standards

**Review by avinashmadhwani02 — APPROVED** [review]

**Review by PratyushGar — APPROVED** [review]

**Review by devinder-harness — APPROVED** [review]

**Comment by kalyansai-harness** [comment]
@MondalSayantan let me talk to design team. Why do we need a one click on respective module and also click on continue button both

**Pull request merged**
