### PR TITLE
fix: [LWG-1258]: fixed schedule title and description text changes

### PR DESCRIPTION
**Pull request by rishik30**
##### Screenshots:

**BEFORE**
Screenshot 2022-02-21 at 11 17 39 PM
Screenshot 2022-02-21 at 11 18 36 PM

**AFTER**
Screenshot 2022-02-21 at 11 18 06 PM
Screenshot 2022-02-21 at 11 18 23 PM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by rishik30** [comment]
retrigger titlecheck

**Comment by rishik30** [comment]
retrigger titlecheck

**Comment by rishik30** [comment]
retrigger jest

**Comment by rishik30** [comment]
retrigger jest

**Review by shalinlk — APPROVED** [review]

**Pull request merged**
