### PR TITLE
feat: [CDS-46882]: created modal UI for model version info

### PR DESCRIPTION
**Pull request by RajBaviskar**
### Summary

- created modal UI for model version info 
#### Screenshots

Screen Shot 2022-12-19 at 12 24 26 PM

Screen Shot 2022-12-07 at 2 59 39 PM

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [x] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [x] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by RajBaviskar** [comment]
Screen Shot 2022-12-19 at 12 24 26 PM
Screen Shot 2022-12-19 at 12 24 20 PM

**Comment by RajBaviskar** [comment]
retrigger titlecheck

**Review by douglasnfrazao — APPROVED** [review]

**Review by tan-nhu — DISMISSED** [review]

**Comment by RajBaviskar** [comment]
retrigger jest

**Review by abhinavrastogi-harness — CHANGES_REQUESTED** [review]
Few concerns:
1. We should not be showing the string `${build.fullVersion}`... it should show the actual version if available
2. We should not be showing "Coming Soon"
3. Service versions are also available on the account settings page (eg. https://app.harness.io/ng/#/account/vpCkHKsDSxK9_KYfjCTMKA/settings/overview) and this change seems redundant

Can we discuss this on a call along with the concerned PM?

**Review by abhinavrastogi-harness — DISMISSED** [review]

**Comment by RajBaviskar** [comment]
retrigger jest

**Comment by RajBaviskar** [comment]
retrigger coverage

**Comment by RajBaviskar** [comment]
retrigger jest

**Comment by RajBaviskar** [comment]
retrigger coverage

**Comment by RajBaviskar** [comment]
retrigger cypress-cd

**Comment by RajBaviskar** [comment]
retrigger jest

**Comment by RajBaviskar** [comment]
retrigger coverage

**Comment by RajBaviskar** [comment]
retrigger coverage

**Comment by RajBaviskar** [comment]
retrigger cypress-cd

**Comment by RajBaviskar** [comment]
retrigger jest

**Comment by RajBaviskar** [comment]
retrigger jest

**Review by abhinavrastogi-harness — APPROVED** [review]

**Comment by RajBaviskar** [comment]
retrigger coverage

**Comment by RajBaviskar** [comment]
retrigger jest

**Comment by RajBaviskar** [comment]
retrigger cypress-cd

**Comment by RajBaviskar** [comment]
retrigger cypress-cd

**Comment by RajBaviskar** [comment]
retrigger cypress-cd

**Comment by RajBaviskar** [comment]
retrigger cypress-cd

**Review by kapilkumawat86 — APPROVED** [review]

**Review by abhinavrastogi-harness — APPROVED** [review]

**Pull request merged**
