### PR TITLE
refactor: [SRM-11546]: Replaced ERROR_TRACKING_ENABLE FF with CVNG_ENABLED

### PR DESCRIPTION
**Pull request by abeg777**
### Summary

Replaced ERROR_TRACKING_ENABLE FF with CVNG_ENABLED

#### Screenshots

NA

### CODE REVIEW

**Comment by abeg777** [comment]
trigger rebase

**Comment by abeg777** [comment]
retrigger cypress

**Comment by abeg777** [comment]
trigger cypress

**Comment by abeg777** [comment]
retrigger build

**Comment by abeg777** [comment]
retrigger prettier

**Comment by abeg777** [comment]
retrigger cypress

**Comment by abeg777** [comment]
retrigger cypress

**Comment by abeg777** [comment]
trigger cypress

**Comment by abeg777** [comment]
trigger cypress

**Comment by abeg777** [comment]
trigger cypress

**Comment by abeg777** [comment]
trigger cypress

**Comment by abeg777** [comment]
trigger cypress

**Review by tan-nhu — APPROVED** [review]

**Review by mtran7 — APPROVED** [review]

**Review by Eric761 — APPROVED** [review]

**Review by upadhyay-an — APPROVED** [review]

**Review by harshilbits — APPROVED** [review]

**Pull request merged**
