### PR TITLE
feat: [PIE-5119]: Allowed values support

### PR DESCRIPTION
**Pull request by chetanvekariya-harness**
#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* Code issue 5 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10916)

**Comment by ishantmehtaharness** [comment]
retrigger jest

**Comment by ishantmehtaharness** [comment]
trigger cypress

**Comment by chetanvekariya-harness** [comment]
retrigger coverage

**Review by ishantmehtaharness — APPROVED** [review]
Looks Good
Thank You @cd-ui

**Comment by ishantmehtaharness** [comment]
retrigger jest

**Comment by ishantmehtaharness** [comment]
This is passing on local
src/modules/72-triggers/pages/triggers/__tests__/SchedulePanel.test.tsx

**Comment by ishantmehtaharness** [comment]
Sonar is failing fue to 10% duplicacy
Coverage is failing because of this: src/modules/72-triggers/pages/triggers/__tests__/SchedulePanel.test.tsx, which is passing on local

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
