### PR TITLE
feat: [CDS-77520]: added new default setting for enabling bi-directional git-sync

### PR DESCRIPTION
**Pull request by vikrant-harness**
### Summary

Problem Statement :-  For Bringing CG-NG parity for `GIT-X` we need bi-directional sync for entities for new simplified gitX like it used to be the case for old gitX. 

Pain Points:- We faced issues with old gitX because of the same.

Solution:- So this time rather than globally doing it we will be enabling it for specific repos / folders through exposing `webhooks` in UI.

This PR targets adding the bi-directional sync gitX setting in the account resources tab.

#### Screenshots

https://github.com/harness/harness-core-ui/assets/106532291/841b1017-d2ca-4a7b-bc46-559867834d37

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by pankajsingh-harness — APPROVED** [review]

**Review by sunnykesh-harness — APPROVED** [review]

**Comment by vikrant-harness** [comment]
retrigger cypress-rest

**Comment by vikrant-harness** [comment]
retrigger cypress-cd

**Comment by vikrant-harness** [comment]
retrigger cypress-pipeline

**Comment by vikrant-harness** [comment]
retrigger cypress-cv

**Pull request merged**
