### PR TITLE
feat: [SRM-10563]: Change Card SLO API changes

### PR DESCRIPTION
**Pull request by shashidhargg**
##### Summary:

SLO API changes in Change Event Card

##### Jira Links:

https://harness.atlassian.net/browse/SRM-10563

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by shashidhargg** [comment]
retrigger coverage

**Review by praneshg239 — DISMISSED** [review]

**Comment by praneshg239** [comment]
retrigger jest

**Comment by praneshg239** [comment]
trigger cypress

**Comment by praneshg239** [comment]
trigger cypress

**Review by deepesh-ui — DISMISSED** [review]

**Review by vasuki-kalluri — DISMISSED** [review]

**Comment by praneshg239** [comment]
trigger cypress

**Review by deepesh-ui — APPROVED** [review]

**Pull request merged**
