### PR TITLE
fix: [SMP-2125]: Fix ingress Annotation for next-gen-ui

### PR DESCRIPTION
**Pull request by arya-harness**
### Summary
Issue: Annotation field missing for next-gen-ui ingress templates.
Fix: Added the field
image

tested with above configurations and found no issues on templating
image

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by akshay-khole** [comment]
what testing needs to be done?

**Comment by arya-harness** [comment]
> what testing needs to be done?

Tested with local templating and the global.ingress.annotation field as the customer did. The screenshots of the test case is in the PR description

**Review by kapilgarg1996 — DISMISSED** [review]

**Review by akshay-khole — APPROVED** [review]

**Comment by akshay-khole** [comment]
@abhinavrastogi-harness  could you please merge this change, needed for smp release

**Comment by arya-harness** [comment]
retrigger jest
retrigger prettier
retrigger typecheck
retrigger eslint
retrigger sonar
retrigger standards
retrigger build
retrigger titlecheck
trigger featurenamecheck
retrigger coverage
trigger rebase
retrigger cypress-rest
retrigger cypress-cd
retrigger cypress-pipeline
retrigger cypress-cv
fix prettier

**Pull request merged**
