### PR TITLE
feat: [CDS-41177]: help panels for service pages , git hub connector …

### PR DESCRIPTION
**Pull request by dhruvUpadhyay07**
…,environemnt pages

#### Screenshots

https://user-images.githubusercontent.com/64455881/182140255-fd06240e-f2c9-449b-9f89-13c72acacf59.mov

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by ishantmehtaharness — APPROVED** [review]
Looks Good

**Comment by dhruvUpadhyay07** [comment]
retrigger coverage

**Comment by dhruvUpadhyay07** [comment]
retrigger jest

**Comment by dhruvUpadhyay07** [comment]
retrigger coverage

**Comment by dhruvUpadhyay07** [comment]
retrigger jest

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10326)

**Review by vkbansal — APPROVED** [review]

**Review by ishantmehtaharness — APPROVED** [review]
Looks Good @dhruvUpadhyay07

**Review by kapilkumawat86 — APPROVED** [review]

**Review by abhinavrastogi-harness — APPROVED** [review]

**Pull request merged**
