### PR TITLE
fix: [PL-26644]: update uicore version

### PR DESCRIPTION
**Pull request by sumanmabd**
### Summary

Updating uicore version

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by sumanmabd** [comment]
trigger cypress

**Comment by sumanmabd** [comment]
retrigger jest

**Comment by sumanmabd** [comment]
retrigger jest

**Comment by sumanmabd** [comment]
retrigger titlecheck

**Review by abhinavrastogi-harness — APPROVED** [review]
Avinash has confirmed that all changes in uicore since `3.72.0` are backwards compatible

**Review by avinashmadhwani02 — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
