### PR TITLE
fix: [SRM-10759]: Add new resource type for SLO

### PR DESCRIPTION
**Pull request by vasuki-kalluri**
##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by vasuki-kalluri** [comment]
image

**Comment by vasuki-kalluri** [comment]
image

**Comment by vasuki-kalluri** [comment]
retrigger titlecheck

**Review by praneshg239 — APPROVED** [review]

**Review by avinashmadhwani02 — APPROVED** [review]

**Review by tan-nhu — APPROVED** [review]

**Comment by vasuki-kalluri** [comment]
retrigger cypress

**Comment by vasuki-kalluri** [comment]
trigger cypress

**Comment by vasuki-kalluri** [comment]
trigger cypress

**Pull request merged**
