### PR TITLE
fix: [PIE-7606]: dropdown filter to work on query change

### PR DESCRIPTION
**Pull request by udayvunnam**

### CODE REVIEW

**Review by pankajsingh-harness — DISMISSED** [review]

**Comment by udayvunnam** [comment]
retrigger typecheck

**Comment by udayvunnam** [comment]
retrigger typecheck

**Review by sonaligoyal-harness — APPROVED** [review]

**Review by pankajsingh-harness — APPROVED** [review]

**Review by sunnykesh-harness — APPROVED** [review]

**Comment by udayvunnam** [comment]
retrigger cypress-rest

**Comment by udayvunnam** [comment]
retrigger jest

**Comment by udayvunnam** [comment]
retrigger cypress-rest

**Comment by udayvunnam** [comment]
retrigger cypress-pipeline

**Comment by udayvunnam** [comment]
retrigger cypress-rest

**Pull request merged**
