### PR TITLE
fix: [CDS-82691]: added runtime support for export vars key

### PR DESCRIPTION
**Pull request by sahithikolichala**
### Summary

- Adds runtime support for export vars key
- Adds runtime validation for Publish Variable Names (Alias)

Test case scenarios: 
- Step edit form
- Step runtime input on RPF
- Step template view

#### Screenshots

https://github.com/harness/harness-core-ui/assets/100121280/e4817470-7812-4961-99b7-eb59276d897e

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

Problem: 
Runtime support for Export vars key field is missing

Solution:
Added runtime support for export vars key field

### CODE REVIEW

**Comment by sahithikolichala** [comment]
trigger messagecheck

**Comment by sahithikolichala** [comment]
retrigger jest

**Comment by sahithikolichala** [comment]
retrigger eslint

**Review by cjlee01 — APPROVED** [review]

**Review by devinder-harness — APPROVED** [review]

**Review by Eric761 — APPROVED** [review]

**Comment by Eric761** [comment]
trigger messagecheck

**Pull request merged**
