### PR TITLE
feat: [CDS-87099]: start using new API contract for pipeline and inpu…

### PR DESCRIPTION
**Pull request by karansaraswat19**
…t sets and change the popover icon for gitness

### Summary

Started using isHarnessCodeRepo query param in pipeline and input set create APIs
And changed the git icon for the code source popover

#### Screenshots

Screenshot 2023-12-18 at 6 39 57 PM (2)

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

### CODE REVIEW

**Review by Eric761 — APPROVED** [review]

**Comment by karansaraswat19** [comment]
trigger messagecheck

**Review by shaurya-harness — APPROVED** [review]

**Review by srdjan-harness — DISMISSED** [review]

**Review by sunnykesh-harness — COMMENTED** [review]
Have some minor comments and plz fix the failing tests.

**Review by ishantmehtaharness — APPROVED** [review]
looks good to me

**Review by shaurya-harness — APPROVED** [review]

**Review by sunnykesh-harness — APPROVED** [review]
Please approve the review comments in follow up PR.

**Review by srdjan-harness — APPROVED** [review]

**Review by sonaligoyal-harness — APPROVED** [review]

**Pull request merged**
