### PR TITLE
fix: [FFM-9743]: Send FeatureIDs parameter as exploded array

### PR DESCRIPTION
**Pull request by davejohnston**
### Summary

This change adds  queryParamStringifyOptions `{arrayFormat: 'repeat'}` to the UseGet request for the onboarding flow to ensure the query parameters are correctly formatted.

#### Background
The current ff-server as well as the platform services conform to the openapi spec 3.X The default rules for the serialization of query parameters are:
```style=form and explode=true```

See https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#fixed-fields-10

This means that for a query parameter `foo` that is a string array, the data should be passed
like:
 ```foo=one&foo=two```

By default restful-react passes the parameters as
```
foo[0]=one&foo[1]=two
```
The option `{arrayFormat: 'repeat'}` modifies this behaviour.

See for other examples of where this is being used in other modules:
* https://github.com/harness/harness-core-ui/pull/14295
* https://github.com/harness/harness-core-ui/pull/6300
* https://github.com/harness/harness-core-ui/commit/8df0bc72249efd5263b035e7e10c963221caa7e3#diff-4a7e03ffbbfa5451e08dc811f5d7166234727efbcf51114534c4fbc702446464R112

##### Before
Screenshot 2023-11-09 at 14 37 09
##### After
Screenshot 2023-11-09 at 22 27 15

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

### CODE REVIEW

**Comment by davejohnston** [comment]
This should be ready for review

**Review by laura-mannus — APPROVED** [review]
You rock! ⭐

**Review by knagurski — APPROVED** [review]
Great job and thanks for proving us wrong! I'll read the docs next time!

**Comment by knagurski** [comment]
trigger messagecheck

**Comment by knagurski** [comment]
Force merged due to lack of coverage in the test file. The suite is currently disabled and will be replaced in the coming weeks.

**Pull request merged**
