### PR TITLE
fix: [CDS-52442]: implement new UX for manifest addition flow for GoogleCloudFunctionDefinition manifest

### PR DESCRIPTION
**Pull request by chetanvekariya-harness**
### Summary
- Implement new manifest UX
- Fix buckets API response consumption
- Allow only one artifact addition

#### Screenshots
**When NO manifests are present:**
Screenshot 2023-02-02 at 12 52 27 PM

**After manifest is added:**
Screenshot 2023-02-02 at 12 53 46 PM

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by satyam-harness — APPROVED** [review]

**Review by vkbansal-harness — APPROVED** [review]

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Comment by chetanvekariya-harness** [comment]
retrigger cypress-pipeline

**Comment by chetanvekariya-harness** [comment]
retrigger cypress-cv

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Review by ishantmehtaharness — APPROVED** [review]
Looks Good

**Pull request merged**
