### PR TITLE
fix: [OPA-447]: Corrected OPA audit url for org and account level events

### PR DESCRIPTION
**Pull request by stuart-mcdonnell**
##### Summary:

Corrected OPA audit url for org and account level events

##### Jira Links:

https://harness.atlassian.net/browse/OPA-447

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by stuart-mcdonnell** [comment]
trigger cypress

**Comment by stuart-mcdonnell** [comment]
retrigger cypress

**Review by tan-nhu — DISMISSED** [review]

**Review by kylekstewart — APPROVED** [review]

**Comment by stuart-mcdonnell** [comment]
trigger cypress

**Comment by stuart-mcdonnell** [comment]
trigger cypress

**Comment by stuart-mcdonnell** [comment]
trigger cypress

**Comment by stuart-mcdonnell** [comment]
trigger cypress

**Review by knagurski — APPROVED** [review]
Nice and simple 👍🏻

**Review by kylekstewart — APPROVED** [review]

**Pull request merged**
