### PR TITLE
fix: [FFM-2489]: extended timeout out for test

### PR DESCRIPTION
**Pull request by crystal-fong**
##### Summary:
A test in `SectionToggle` may have timed out resulting it to fail. Increasing the default time out to prevent it from happening again

##### Jira Links:
https://harness.atlassian.net/browse/FFM-2489

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by crystal-fong** [comment]
retrigger titlecheck

**Comment by crystal-fong** [comment]
retrigger titlecheck

**Comment by crystal-fong** [comment]
trigger cypress

**Review by knagurski — APPROVED** [review]
LGTM

**Review by chrisblakely01 — APPROVED** [review]

**Pull request merged**
