### PR TITLE
feat: [CDS-51549]:improvements-filestore-ux

### PR DESCRIPTION
**Pull request by litvinovstas**
### Summary
Added resize for left sidebar (now it's flexible)
Improved spaces for columns inside folders. (right side)
Improved names for folder and files sorting.
Changed name 'Sort folder by'

#### Screenshots
Screenshot 2023-01-24 at 16 48 06
Screenshot 2023-01-24 at 16 49 17

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by litvinovstas** [comment]
retrigger jest

**Comment by litvinovstas** [comment]
retrigger jest

**Comment by litvinovstas** [comment]
retrigger titlecheck

**Comment by litvinovstas** [comment]
retrigger cypress-cv

**Comment by litvinovstas** [comment]
retrigger cypress-cv

**Review by radujomir — APPROVED** [review]

**Comment by litvinovstas** [comment]
retrigger cypress-cv

**Review by YounixIO — APPROVED** [review]

**Pull request merged**
