### PR TITLE
refactor: [STO-4511]: Replace custom mounter with ChildAppMounter

### PR DESCRIPTION
**Pull request by chris-harness**
##### Summary:

- Adds the STO MFE  types to the `@harness/microfrontend` package
- Unifies federated mounting of STO via `ChildAppMounter`

##### Jira Links:

https://harness.atlassian.net/browse/STO-4511

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Review by tan-nhu — APPROVED** [review]

**Comment by chris-harness** [comment]
trigger cypress

**Review by vkbansal — APPROVED** [review]

**Comment by chris-harness** [comment]
trigger cypress

**Comment by chris-harness** [comment]
retrigger cypress

**Comment by chris-harness** [comment]
trigger cypress

**Review by abhinavrastogi-harness — APPROVED** [review]

**Review by knagurski — APPROVED** [review]
👍🏻

**Pull request merged**
