### PR TITLE
fix: [FFM-3577]: Updating the font in TG List to match UX specifications

### PR DESCRIPTION
**Pull request by laura-mannus**
### Summary

  Font should match design provided by UX on the Target Groups Listing page.

#### Screenshots

image

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by knagurski — APPROVED** [review]
I'm not sure... this PR is kinda complicated 😛

**Review by crystal-fong — DISMISSED** [review]

**Review by crystal-fong — DISMISSED** [review]

**Comment by laura-mannus** [comment]
retrigger standards

**Review by knagurski — DISMISSED** [review]
🔥

**Comment by laura-mannus** [comment]
retrigger standards

**Comment by laura-mannus** [comment]
retrigger cypress

**Comment by laura-mannus** [comment]
trigger cypress

**Review by chrisblakely01 — APPROVED** [review]

**Review by crystal-fong — APPROVED** [review]

**Comment by laura-mannus** [comment]
trigger cypress

**Comment by laura-mannus** [comment]
trigger cypress

**Pull request merged**
