### PR TITLE
fix: [CVS-9064]: Cypress tests for Verify step - fix falkiness

### PR DESCRIPTION
**Pull request by praneshg239**
##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by praneshg239** [comment]
retrigger jest

**Comment by praneshg239** [comment]
retrigger jest

**Comment by praneshg239** [comment]
retrigger jest

**Review by bhavya-sinha — APPROVED** [review]

**Review by meenakshi-harness — APPROVED** [review]

**Comment by meenakshi-harness** [comment]
retrigger jest

**Comment by vkbansal** [comment]
Merging this as the failing jest test is already fixed in master

**Pull request merged**
