### PR TITLE
fix: [CDS-83659]: fixed requirment of two clicks to open fields dialog due to unnecessary usage of extra level of component

### PR DESCRIPTION
**Pull request by satyam-harness**
### Summary
Problem - In servicenow steps, clicking on + Fields the very first time does not open field dialog box instead focus is removed from short description textarea, on second click add field menu appears.

Solution - Due to extra layer of component drill, click event was not getting passed to text properly. Removed usage of component.

Testcases - 
Cannt be tested using jest, as we already have one `Open a saved step - edit stage view` testcase, in which we type in description and then click on addField and it works fine.

This can be tested using cypress, will add once changes are in QA. Created ticket https://harness.atlassian.net/browse/CDS-84703.

Manual Testing - 

- Checked if fields dialog is opening on one click with focus on description field in both serviceNow create/update step.

#### Screenshots

Before - 

https://github.com/harness/harness-core-ui/assets/96036463/8a089ecf-de85-4fc6-b43a-56459ddce047

After - 

https://github.com/harness/harness-core-ui/assets/96036463/370ed8bd-1a16-44c0-9e51-ee5a0fc85cb7

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

### CODE REVIEW

**Comment by satyam-harness** [comment]
trigger messagecheck

**Comment by satyam-harness** [comment]
retrigger eslint

**Comment by satyam-harness** [comment]
retrigger eslint

**Comment by satyam-harness** [comment]
retrigger eslint

**Comment by satyam-harness** [comment]
retrigger eslint

**Review by samarth-sharma31 — APPROVED** [review]

**Review by chetanvekariya-harness — COMMENTED** [review]
Do we know why this happened ? This has to be common component and should be reused at both places. This might not be actual reason for issue.
Also, we do not need cypress for this trivial issue. Cypress should be written only for critical use cases. This could have been caught in manual testing and once fixed will not happen again. Unless someone does not test manually after touching this code.

**Comment by satyam-harness** [comment]
> Do we know why this happened ? This has to be common component and should be reused at both places. This might not be actual reason for issue. Also, we do not need cypress for this trivial issue. Cypress should be written only for critical use cases. This could have been caught in manual testing and once fixed will not happen again. Unless someone does not test manually after touching this code.

@chetanvekariya-harness  root cause is not yet known, tried multiple things but no luck. And also generalising this button for both the steps for reusing will be little messy, as it uses a modal hook `showDynamicFieldsModal` and that modal hook has several dependencies.

**Pull request merged**
