### PR TITLE
refactor: [GTM-1005]: replace useCommunity hook with util method

### PR DESCRIPTION
**Pull request by nanaxuHarness**
##### Summary:

this is to replace hooks `useCommunity` with util method so that:

1) `useCommunity` relies on CD license, in which some cases, the CD license can get failed being created, which we have heard complains from community users. by using the util method, which relies on deploymentType, we will relieve this issue to some extent, like on subscription pages.
2) deploymentType is more reliable than license.

##### Jira Links:
https://harness.atlassian.net/browse/PLG-1005

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by nanaxuHarness** [comment]
trigger cypress

**Comment by mayankVermaHarness** [comment]
`useCommunity relies on CD license, in which some cases, the CD license can get failed being created, which we have heard complains from community users. by using the util method, which relies on deploymentType, we will not have such issue.`

Can we also find out as to why the license creation gets failed? Just curious

**Review by mayankVermaHarness — APPROVED** [review]

**Comment by nanaxuHarness** [comment]
> 

it's intermittent, not sure the root cause yet, but we do have a story to track this: https://harness.atlassian.net/browse/PLG-705

**Comment by nanaxuHarness** [comment]
trigger cypress

**Review by kapilkumawat86 — APPROVED** [review]

**Review by desagnik — APPROVED** [review]
Looks fine to me.

**Pull request merged**
