### PR TITLE
feat: [CDS-57946]: Change default-populated value in UI for pipelineBranchName

### PR DESCRIPTION
**Pull request by pankajsingh-harness**
### Summary
 Changed default-populated value in UI for pipelineBranchName from <+trigger.branch> to <+trigger.payload.branch>

#### Screenshots
**Before:**
Screenshot 2023-05-05 at 6 10 34 PM

**After:**
Screenshot 2023-05-05 at 6 09 44 PM

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by pankajsingh-harness** [comment]
retrigger titlecheck

**Comment by pankajsingh-harness** [comment]
trigger featurenamecheck

**Comment by pankajsingh-harness** [comment]
retrigger titlecheck

**Comment by pankajsingh-harness** [comment]
trigger featurenamecheck

**Review by rameshx — APPROVED** [review]

**Review by Sagar-Rajput7 — APPROVED** [review]

**Comment by pankajsingh-harness** [comment]
Coverage is failing:
```
Jest: "global" coverage threshold for statements (65%) not met: 46.29%
Jest: "global" coverage threshold for branches (50%) not met: 22.64%
Jest: "global" coverage threshold for lines (65%) not met: 43.79%
Jest: "global" coverage threshold for functions (50%) not met: 31.63%
```
Screenshot 2023-05-09 at 4 44 55 PM

**Review by AshwinBhatkal-Harness — APPROVED** [review]

**Review by YounixIO — APPROVED** [review]

**Pull request merged**
