### PR TITLE
fix: [CI-5580]: deprecate service dependency for CI and fix read only scenarios

### PR DESCRIPTION
**Pull request by shaurya-harness**
### Summary

deprecate service dependency for CI and fix read only scenarios
fixes [CI-5891](https://harness.atlassian.net/browse/CI-5891) and [CI-5525](https://harness.atlassian.net/browse/CI-5525) as well
 please see screenshots attached for reference
 
#### Screenshots

Screenshot 2022-11-03 at 2 36 49 PM
Screenshot 2022-11-03 at 2 36 59 PM
Screenshot 2022-11-03 at 2 50 08 PM
Screenshot 2022-11-03 at 2 50 21 PM

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by shaurya-harness** [comment]
retrigger jest

**Comment by shaurya-harness** [comment]
retrigger jest

**Comment by shaurya-harness** [comment]
retrigger jest

**Comment by shaurya-harness** [comment]
retrigger cypress-cv

**Comment by shaurya-harness** [comment]
retrigger cypress-pipeline

**Review by vardanbansal-harness — DISMISSED** [review]

**Review by pankajsingh-harness — APPROVED** [review]

**Review by vardanbansal-harness — APPROVED** [review]

**Review by pankajsingh-harness — APPROVED** [review]

**Pull request merged**
