### PR TITLE
feat: [CDS-47128]: force delete envgroup

### PR DESCRIPTION
**Pull request by RajBaviskar**
### Summary

- force delete envgroup

https://user-images.githubusercontent.com/7086440/213390249-e0bbe4ce-ccfc-4371-a939-24c1fb72d553.mov

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by RajBaviskar** [comment]
retrigger cypress-cd

**Comment by RajBaviskar** [comment]
retrigger jest

**Comment by RajBaviskar** [comment]
retrigger cypress-cd

**Comment by RajBaviskar** [comment]
retrigger cypress-cd

**Comment by RajBaviskar** [comment]
retrigger cypress-cd

**Comment by RajBaviskar** [comment]
retrigger jest

**Comment by RajBaviskar** [comment]
retrigger jest

**Review by AshwinBhatkal-Harness — APPROVED** [review]

**Review by tan-nhu — APPROVED** [review]

**Pull request merged**
