### PR TITLE
fix: [PL-31104]: Hotfix pl 31103

### PR DESCRIPTION
**Pull request by tiwaritejas**
### Summary

Scim users cannot be removed from orgs and projects in the current state. This PR removes this restriction as it is a valid use case because Scim provisioning is done only at the account level in Harness.

Corresponding develop PR: https://github.com/harness/harness-core-ui/pull/13692

Testing:-
Tested this behaviour in localdev by trying to delete the Scim added user with and without the FF that has been introduced for this feature. Working as expected.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by tiwaritejas** [comment]
retrigger jest

**Comment by tiwaritejas** [comment]
retrigger jest

**Review by mayankVermaHarness — APPROVED** [review]

**Review by meenakshi-harness — APPROVED** [review]

**Comment by tiwaritejas** [comment]
retrigger coverage

**Comment by tiwaritejas** [comment]
retrigger cypress-cv

**Comment by tiwaritejas** [comment]
retrigger cypress-pipeline

**Pull request merged**
