### PR TITLE
fix: [SEI-3139]: SEI showing up without feature flag (#17788)

### PR DESCRIPTION
**Pull request by sharath-levelops**
* fix: [SEI-3139]: SEI showing up without feature flag

* Update ModuleList.test.tsx.snap

### Summary

Hotfix the SEI display without feature flag issue to QA

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[SEI-3139]: https://harness.atlassian.net/browse/SEI-3139?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by sharath-levelops** [comment]
retrigger cypress-rest

**Comment by sharath-levelops** [comment]
retrigger cypress-cv

**Comment by sharath-levelops** [comment]
retrigger cypress-rest

**Comment by sharath-levelops** [comment]
retrigger cypress-cd

**Comment by sharath-levelops** [comment]
retrigger cypress-rest

**Comment by sharath-levelops** [comment]
retrigger cypress-cv

**Comment by sharath-levelops** [comment]
retrigger cypress-cd

**Review by knagurski — APPROVED** [review]
👍🏻

**Review by harshilbits — APPROVED** [review]

**Review by sunnykesh-harness — APPROVED** [review]

**Review by sunnykesh-harness — APPROVED** [review]

**Review by knagurski — APPROVED** [review]

**Pull request merged**
