### PR TITLE
feat: [CCM-5845]: render custom domain for k8s rule

### PR DESCRIPTION
**Pull request by rishik30**
##### Screenshots:

Screenshot 2022-02-28 at 6 06 44 PM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by rishik30** [comment]
retrigger jest

**Comment by rishik30** [comment]
trigger sonar

**Comment by rishik30** [comment]
retrigger sonar

**Comment by rishik30** [comment]
retrigger jest

**Review by riyasyash — DISMISSED** [review]

**Review by shalinlk — DISMISSED** [review]

**Comment by rishik30** [comment]
retrigger jest

**Review by jenil-harness — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
