### PR TITLE
fix: [PL-39289]: Added path rewrite for audit service in local

### PR DESCRIPTION
**Pull request by avinashmadhwani02**
#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by tan-nhu — APPROVED** [review]

**Comment by abhinavrastogi-harness** [comment]
The rewrite was removed earlier: https://github.com/harness/harness-core-ui/pull/11284/files

Please confirm if this change works for all environments and API_URL combinations.

**Comment by avinashmadhwani02** [comment]
> The rewrite was removed earlier: https://github.com/harness/harness-core-ui/pull/11284/files
> 
> Please confirm if this change works for all environments and API_URL combinations.

re-write is added only when the target url is localhost, for other cases it's still the same. 
It was breaking when pointing to locahost, hence this will fix it

**Comment by avinashmadhwani02** [comment]
retrigger titlecheck

**Review by abhinavrastogi-harness — APPROVED** [review]
how come other services don't need conditional rewriting? is the audit service not have a standard implementation? please follow-up with the BE team once

**Pull request merged**
