### PR TITLE
fix: [PL-21367]: Tags are not displayed on mouse hover on Filter icon

### PR DESCRIPTION
**Pull request by ishantmehtaharness**
description about the change:
tags ia an object here, and the filter component needs it as an array to be render it

required screen shots or Videos about the fix
Attached screenshot

area impacted with the fix
This change is specific to Filter in connectors, so no other area should be impacted

test cases tested for the fix
I have tested it for empty tags, and another scenario with tags.
API calls are also working fine in both the cases

Screenshot 2023-11-20 at 2 13 15 PM

### CODE REVIEW

**Comment by ishantmehtaharness** [comment]
trigger messagecheck

**Comment by ishantmehtaharness** [comment]
trigger messagecheck

**Comment by ishantmehtaharness** [comment]
trigger messagecheck

**Comment by ishantmehtaharness** [comment]
trigger messagecheck

**Review by litvinovstas — APPROVED** [review]

**Review by pankajsingh-harness — APPROVED** [review]

**Review by namanharness — APPROVED** [review]

**Pull request merged**
