### PR TITLE
fix: [CDS-33647]: correct storeType label for Gitlab

### PR DESCRIPTION
**Pull request by abhinavsingh1196**
##### Summary:

Gitlab storetype label corrected to 'Gitlab' instead of 'GitLab'.
harness-core PR: https://github.com/harness/harness-core/pull/30875

##### Jira Links:
https://harness.atlassian.net/browse/CDS-33647

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by abhinavsingh1196** [comment]
retrigger titlecheck

**Review by bhavya-sinha — CHANGES_REQUESTED** [review]

**Comment by abhinavsingh1196** [comment]
retrigger jest

**Review by bhavya-sinha — APPROVED** [review]

**Comment by bhavya-sinha** [comment]
LGTM. @abhinavsingh1196 Have you tested the flow with gitlab manifest store type, and saving the pipeline?
Please make sure the pipeline is saved with this, because i remember changing GitLab and Gitlab to and fro earlier also.

**Comment by abhinavsingh1196** [comment]
> LGTM. @abhinavsingh1196 Have you tested the flow with gitlab manifest store type, and saving the pipeline? Please make sure the pipeline is saved with this, because i remember changing GitLab and Gitlab to and fro earlier also.

@bhavya-sinha yes, tested it by creating a pipeline with a Gitlab manifest.

**Review by YounixIO — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
