### PR TITLE
feat: [CI-3378]: trigger yaml revert previous version

### PR DESCRIPTION
**Pull request by mtran7**
##### Screenshots:

Added Error Strip to surface pipeline input errors & api errors for pipeline yaml structure when validating Visual or YAML view. Highlighting fields for visual will be done in future PR for both CI Codebase highlighting & stages fields highlighting
image

Typically user will not delete pre-filled branch, tag, PR value. But this highlighting appears sometimes
image

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by mtran7** [comment]
retrigger typecheck

**Review by vardanbansal-harness — DISMISSED** [review]

**Comment by mtran7** [comment]
retrigger jest

**Review by anjanBalgovind — APPROVED** [review]

**Review by tan-nhu — APPROVED** [review]

**Comment by mtran7** [comment]
retrigger jest

**Comment by mtran7** [comment]
image
Cognitive complexity will be handled in a future PR

**Pull request merged**
