### PR TITLE
feat: [PIE-5180]: enabled 'NotifyOnlyMe' feature upon running a pipeline

### PR DESCRIPTION
**Pull request by Eric761**
### Summary

When we run a pipeline, there is a checkbox `Notify only me about execution status` that when checked, Notifications (Email) will now be sent only to the user who triggered the pipeline, bypassing all other previously configured Notifications.
It should be noted that in the initial phase of development, it is hardcoded for only two events: pipeline start and pipeline end.

#### Demo Video

https://user-images.githubusercontent.com/73639897/190960288-d5e3227e-5081-49a9-8075-af236e6b04d6.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11288)

**Comment by Eric761** [comment]
retrigger titlecheck

**Comment by Eric761** [comment]
retrigger jest

**Comment by Eric761** [comment]
trigger cypress

**Review by vkbansal-harness — APPROVED** [review]

**Review by sonaligoyal-harness — APPROVED** [review]

**Pull request merged**
