### PR TITLE
fix: [CDS-84490]: Revert - fix apply templates input call getting cancelled on slow cpu's

### PR DESCRIPTION
**Pull request by pankajsingh-harness**
Reverts harness/harness-core-ui#19255

### CODE REVIEW

**Comment by pankajsingh-harness** [comment]
trigger messagecheck

**Comment by pankajsingh-harness** [comment]
trigger messagecheck

**Comment by pankajsingh-harness** [comment]
trigger messagecheck

**Comment by pankajsingh-harness** [comment]
trigger messagecheck

**Review by sonaligoyal-harness — APPROVED** [review]

**Review by PratyushGar — APPROVED** [review]

**Pull request merged**
