### PR TITLE
feat: [CDS-59090]: show delegate task logs button for service and infra steps in execution view

### PR DESCRIPTION
**Pull request by chetanvekariya-harness**
### Summary
- When stepDetails is not empty, individual delegate task entries for service and infra steps should shown along with Delegate Selection Logs link
- On click of links, respective delegate's logs will be shown in a modal
- When stepDetails is not empty `View Delegate Task Logs` button should be shown
- On click of button, combined delegate logs for all task ids will be shown in a modal
- Test cases for these changes are written as well

#### Screenshots
Screenshot 2023-06-01 at 7 44 09 PM

Screenshot 2023-06-01 at 7 44 21 PM

Screenshot 2023-06-01 at 7 45 45 PM

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by chetanvekariya-harness** [comment]
retrigger titlecheck

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Comment by chetanvekariya-harness** [comment]
retrigger cypress-pipeline

**Comment by chetanvekariya-harness** [comment]
retrigger cypress-cv

**Review by Eric761 — APPROVED** [review]

**Review by PratyushGar — APPROVED** [review]

**Pull request merged**
