### PR TITLE
fix: [CDS-42058]: remove timeout causing validation to flicker

### PR DESCRIPTION
**Pull request by Tamaraius**
### Summary

Removed timeout that caused validation error message to flicker

#### Screenshots

Before video

https://user-images.githubusercontent.com/96610348/185912735-fde32d09-c102-447d-96f8-e6aadbb53eab.mov

After video 

https://user-images.githubusercontent.com/96610348/185912804-d5fd5cc9-30f4-4806-992e-bd9adaf2a5fa.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10682)

**Comment by Tamaraius** [comment]
retrigger titlecheck

**Comment by Tamaraius** [comment]
retrigger titlecheck

**Comment by AshwinBhatkal-Harness** [comment]
We need a new line before and after the uploaded media link to render them inline

**Review by ishantmehtaharness — APPROVED** [review]
Loooks good

**Review by rameshx — APPROVED** [review]

**Pull request merged**
