### PR TITLE
fix: [STO-4459]: Switch to CI steps

### PR DESCRIPTION
**Pull request by r0610205**
##### Summary:

Use CI steps to populate step palette

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by r0610205** [comment]
retrigger jest

**Comment by r0610205** [comment]
retrigger titlecheck

**Comment by r0610205** [comment]
retrigger coverage

**Comment by r0610205** [comment]
retrigger titlecheck

**Review by atmollo-harness — APPROVED** [review]

**Review by chris-harness — APPROVED** [review]

**Review by bhavya-sinha — APPROVED** [review]

**Pull request merged**
