### PR TITLE
feat: [CDB-233]: add dashboards test intelligence module

### PR DESCRIPTION
**Pull request by sean-harness**
##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by sean-harness** [comment]
retrigger jest

**Comment by sean-harness** [comment]
trigger cypress

**Comment by sean-harness** [comment]
trigger cypress

**Comment by sean-harness** [comment]
retrigger typecheck

**Review by Harness-JKhattak — APPROVED** [review]

**Review by knagurski — DISMISSED** [review]
Solid work 👍🏻

**Review by Harness-JKhattak — APPROVED** [review]

**Review by DFieldFL — DISMISSED** [review]

**Review by tan-nhu — DISMISSED** [review]

**Review by chrisblakely01 — APPROVED** [review]

**Review by crystal-fong — APPROVED** [review]

**Pull request merged**
