### PR TITLE
fix: [CDS-52109]: page crash when entering env input values in RPF

### PR DESCRIPTION
**Pull request by AshwinBhatkal-Harness**
### Summary

Page crash when entering env input values in RPF

Develop PR - https://github.com/harness/harness-core-ui/pull/13731

#### Screenshots

https://user-images.githubusercontent.com/96711906/215288559-c1387e48-1727-4510-a655-dc1eaf680471.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by AshwinBhatkal-Harness** [comment]
Closed it as checks were failing and the base branch was develop

**Comment by AshwinBhatkal-Harness** [comment]
retrigger standards

**Comment by AshwinBhatkal-Harness** [comment]
retrigger build

**Comment by AshwinBhatkal-Harness** [comment]
retrigger coverage

**Comment by AshwinBhatkal-Harness** [comment]
retrigger sonar

**Review by vikrant-harness — APPROVED** [review]

**Review by PratyushGar — APPROVED** [review]

**Review by vkbansal-harness — APPROVED** [review]

**Pull request merged**
