### PR TITLE
fix: [BG-37]: error handling for the thrown error

### PR DESCRIPTION
**Pull request by PratyushGar**
##### Summary:

Added try_catch block to capture error thrown

##### Jira Links:

[https://harness.atlassian.net/browse/BG-37](https://harness.atlassian.net/browse/BG-37)

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by PratyushGar** [comment]
retrigger titlecheck

**Comment by PratyushGar** [comment]
retrigger jest

**Comment by PratyushGar** [comment]
retrigger typecheck

**Comment by PratyushGar** [comment]
trigger cypress

**Review by AshwinBhatkal — APPROVED** [review]

**Review by yc147 — APPROVED** [review]

**Review by SagarRajput7 — APPROVED** [review]

**Review by Sagar-Rajput7 — APPROVED** [review]

**Review by satyam-harness — APPROVED** [review]

**Pull request merged**
