### PR TITLE
fix: [FFM-1808]: long flag name now fits within container

### PR DESCRIPTION
**Pull request by crystal-fong**
##### Summary:
Before: Long flag name would overflow out of its container
image

##### Jira Links:
https://harness.atlassian.net/browse/FFM-1808

##### Screenshots:
image

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by crystal-fong** [comment]
retrigger titlecheck

**Comment by crystal-fong** [comment]
retrigger titlecheck

**Comment by crystal-fong** [comment]
trigger cypress

**Comment by crystal-fong** [comment]
retrigger jest

**Comment by crystal-fong** [comment]
retrigger jest

**Review by chrisblakely01 — APPROVED** [review]
Nice and simple fix for the problem. Good Job

**Review by nanaxuHarness — APPROVED** [review]

**Pull request merged**
