### PR TITLE
fix: [IAC-916]: Update IACM module name in expanded side nav

### PR DESCRIPTION
**Pull request by bgribben-harness**
- Updates the IACM module's name in the expanded side nav view
- Adjusts expanded side nav's width to accommodate new longer module title

| **Before** | **w/ Text Change** | **w/ Width Change** |
|--------|-------------|--------------|
| image    | image         | image          |

### CODE REVIEW

**Comment by bgribben-harness** [comment]
retrigger jest

**Comment by bgribben-harness** [comment]
retrigger coverage

**Comment by bgribben-harness** [comment]
retrigger coverage

**Comment by bgribben-harness** [comment]
retrigger jest

**Comment by abhinavrastogi-harness** [comment]
@avinashmadhwani02 please review

**Review by avinashmadhwani02 — APPROVED** [review]

**Review by willd0yle — APPROVED** [review]

**Pull request merged**
