### PR TITLE
fix: [CDS-37301]: enable artifactory artifact trigger for serverless pipelines

### PR DESCRIPTION
**Pull request by chetanvekariya-harness**
##### Summary:

- For Serverless Pipeline, Artifactory Artifact Trigger should be enabled
- For Non Serverless Pipeline, Artifactory Artifact Trigger should keep appearing under Coming Soon section
- Under first step, Select Artifact should display all the artifacts which have artifactPath as Runtime input

##### Jira Links:
https://harness.atlassian.net/browse/CDS-37301

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by chetanvekariya-harness** [comment]
dockerize

**Comment by chetanvekariya-harness** [comment]
retrigger titlecheck

**Comment by chetanvekariya-harness** [comment]
dockerize

**Comment by Sagar-Rajput7** [comment]
dockerize

**Comment by chetanvekariya-harness** [comment]
dockerize

**Review by bhavya-sinha — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
