### PR TITLE
fix: [PIE-2157]: changed the placeholder text for failure strategy step

### PR DESCRIPTION
**Pull request by vikrant-harness**
##### Summary:

Changed the failure strategy step placeholder text

##### Jira Links:

https://harness.atlassian.net/browse/PIE-2157

##### Screenshots:

After:- 
Screenshot 2022-06-15 at 3 22 53 PM

Before:- 

Screenshot 2022-06-15 at 3 24 20 PM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by vikrant-harness** [comment]
retrigger titlecheck

**Comment by vikrant-harness** [comment]
trigger cypress

**Comment by vikrant-harness** [comment]
trigger rebase

**Comment by vikrant-harness** [comment]
trigger cypress

**Review by kapilkumawat86 — APPROVED** [review]

**Review by PratyushGar — APPROVED** [review]

**Pull request merged**
