### PR TITLE
fix: [CDS-36587]: fixed empty state css on cd overview dashboard

### PR DESCRIPTION
**Pull request by Sagar-Rajput7**
##### Jira Links:

https://harness.atlassian.net/browse/CDS-36587

##### Screenshots:

Earlier:
image

Now: 
Screenshot 2022-06-02 at 2 12 55 AM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by Sagar-Rajput7** [comment]
retrigger titlecheck

**Comment by Sagar-Rajput7** [comment]
retrigger jest

**Comment by Sagar-Rajput7** [comment]
trigger cypress

**Review by vkbansal — APPROVED** [review]

**Review by udayvunnam — APPROVED** [review]

**Comment by udayvunnam** [comment]
cards on second should've white background. Will that be a separate PR ?

**Pull request merged**
