### PR TITLE
fix: [CDS-52105]: Fixed name & identifier schema validation for Triggers

### PR DESCRIPTION
**Pull request by pankajsingh-harness**
### Summary

Added the validation for name and identifier in common Validation util as NameIdentifierSchema. Now this schema can be extended anywhere where we need name and identifier schema instead of adding the validation again.

Eg: `NameIdentifierSchema(getString, { nameRequiredErrorMsg?: string; identifierRequiredErrorMsg?: string; identifierRegexErrorMsg?: string }).shape({})`

Ref: [https://github.com/jquense/yup#objectshapefields-object-nosortedges-arraystring-string-schema](https://github.com/jquense/yup#objectshapefields-object-nosortedges-arraystring-string-schema) 

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Comment by pankajsingh-harness** [comment]
retrigger cypress-pipeline

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Review by ishantmehtaharness — APPROVED** [review]

**Review by vkbansal-harness — APPROVED** [review]

**Review by chetanvekariya-harness — APPROVED** [review]

**Pull request merged**
