### PR TITLE
fix: [CDS-48988]: Don't make API calls to fetch information about ACR repository if connectorRef is undefined

### PR DESCRIPTION
**Pull request by douglasnfrazao**
### Summary

When we select the <+input> or <+expression>, `connectorRef`  is `null` and the check to call or not the API was wrong it was being called an API that will always fail

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by douglasnfrazao** [comment]
retrigger jest

**Comment by douglasnfrazao** [comment]
retrigger jest

**Comment by douglasnfrazao** [comment]
retrigger jest

**Comment by douglasnfrazao** [comment]
retrigger titlecheck

**Review by tan-nhu — APPROVED** [review]

**Review by PratyushGar — APPROVED** [review]

**Pull request merged**
