### PR TITLE
fix: [CDS-41810]: runtime validations for command unit step

### PR DESCRIPTION
**Pull request by vikrant-harness**
### Summary

1. Script Validations in case of command type = 'Script'
2. Destination Path validations in case of command type = 'Copy'

#### Screenshots

https://user-images.githubusercontent.com/106532291/188405127-a7555434-33d5-4a42-9a3e-e835f1a3e992.mov

https://user-images.githubusercontent.com/106532291/188719248-3b3f0d46-cf39-4458-aa2e-1bc23c774168.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

## [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11012)

**Comment by vikrant-harness** [comment]
retrigger titlecheck

**Comment by vikrant-harness** [comment]
retrigger jest

**Comment by vikrant-harness** [comment]
trigger cypress

**Review by YounixIO — APPROVED** [review]

**Review by radujomir — APPROVED** [review]

**Review by azharness — APPROVED** [review]

**Comment by vikrant-harness** [comment]
retrigger coverage

**Comment by vikrant-harness** [comment]
retrigger jest

**Review by sonaligoyal-harness — APPROVED** [review]

**Review by YounixIO — APPROVED** [review]

**Pull request merged**
