### PR TITLE
fix: [PIE-2793]: Verifying object store in connected database before any transaction

### PR DESCRIPTION
**Pull request by PratyushGar**
##### Summary:

NotFoundError was coming due to object store not found. Verifying the store presence first in connected database to avoid that.

##### Jira Links:

[https://harness.atlassian.net/browse/PIE-2793](https://harness.atlassian.net/browse/PIE-2793)

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Review by chetanvekariya-harness — DISMISSED** [review]

**Comment by PratyushGar** [comment]
retrigger typecheck

**Comment by devinder-harness** [comment]
retrigger TypeCheck

**Comment by devinder-harness** [comment]
retrigger typecheck

**Comment by devinder-harness** [comment]
retrigger titlecheck

**Review by chetanvekariya-harness — APPROVED** [review]

**Comment by PratyushGar** [comment]
trigger cypress

**Comment by PratyushGar** [comment]
trigger cypress

**Review by devinder-harness — APPROVED** [review]

**Pull request merged**
