### PR TITLE
fix: [CDS-36983]: do not show execution strategies and display deploy step by default for serverless

### PR DESCRIPTION
**Pull request by chetanvekariya-harness**
##### Summary:
- Do not show execution strategies and display deploy step by default for Serverless (display execution strategies as it was appearing for Kubernetes - No Change)
- Write cypress test cases for both scenarios (Serverless and Kubernetes)
- Do not show delete stage data modal if already selected deploy type is clicked by user

##### Jira Links:
https://harness.atlassian.net/browse/CDS-36983

##### Screenshots:

**Serverless:**
Screenshot 2022-05-04 at 10 15 59 AM

**Kubernetes:**
Screenshot 2022-05-04 at 10 16 55 AM

**No Cypress Failures for PipelineCanvas in Local:**
Screenshot 2022-05-06 at 7 06 13 PM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by chetanvekariya-harness** [comment]
dockerize

**Comment by chetanvekariya-harness** [comment]
dockerize

**Comment by chetanvekariya-harness** [comment]
dockerize

**Comment by chetanvekariya-harness** [comment]
dockerize

**Comment by chetanvekariya-harness** [comment]
dockerize

**Comment by chetanvekariya-harness** [comment]
dockerize

**Review by satyam-harness — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
