### PR TITLE
feat: [PLG-1606]: ff clean up

### PR DESCRIPTION
**Pull request by dhruvUpadhyay07**
### Summary

removed 2 flags -  PLANS_ENABLED  and  FREE_PLAN_ENABLED 
SAAS will have the flow as it was when the flags were true and for ON_PREM currently we have kept the flow as when the flags were false 

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by dhruvUpadhyay07** [comment]
retrigger jest

**Comment by dhruvUpadhyay07** [comment]
retrigger coverage

**Comment by dhruvUpadhyay07** [comment]
retrigger cypress-cv

**Comment by dhruvUpadhyay07** [comment]
retrigger cypress-rest

**Review by devinder-harness — APPROVED** [review]

**Review by satyam-harness — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Review by laura-mannus — APPROVED** [review]

**Review by jenil-harness — APPROVED** [review]

**Review by rishik30 — APPROVED** [review]

**Pull request merged**
