### PR TITLE
feat: [SRM-11733] Add paths and container for

### PR DESCRIPTION
**Pull request by David-Kreiner**
live agent list to point to microfrontend

### Summary

Added button on left side of SRM module under the Project Setup dropdown to point to a new agent list page being created on Error Tracking micro-frontend. These changes are hidden behind the feature flag: SRM_ET_EXPERIMENTAL.

#### Screenshots

Before:
image

After:
image

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [x] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by David-Kreiner** [comment]
fix prettier

**Comment by David-Kreiner** [comment]
trigger cypress

**Comment by David-Kreiner** [comment]
trigger jest

**Review by cseverino789 — APPROVED** [review]

**Comment by David-Kreiner** [comment]
trigger rebase

**Pull request closed without merging**
