### PR TITLE
fix: [CDS-43238]: added new tracking constants for onboarding delegate flow

### PR DESCRIPTION
**Pull request by vikrant-harness**
### Summary

added new tracking constants for onboarding delegate flow as per request from PM.

Note: The sonar check is failing due to adding similar events in docker and kubernetes delegate flow.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 9 Issues 
* Code issue 9 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11224)

**Comment by vikrant-harness** [comment]
retrigger jest

**Comment by vikrant-harness** [comment]
retrigger titlecheck

**Comment by vikrant-harness** [comment]
retrigger titlecheck

**Review by Sagar-Rajput7 — APPROVED** [review]

**Review by sonaligoyal-harness — APPROVED** [review]

**Comment by vikrant-harness** [comment]
trigger cypress

**Pull request merged**
