### PR TITLE
fix: [PIE-4283]: inconsistent behaviour of service ref getting cleared from yaml fixed

### PR DESCRIPTION
**Pull request by bhavya-sinha**
##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Review by satyam-harness — APPROVED** [review]

**Review by devinder-harness — DISMISSED** [review]

**Comment by bhavya-sinha** [comment]
retrigger build

**Comment by bhavya-sinha** [comment]
retrigger titlecheck

**Comment by bhavya-sinha** [comment]
trigger cypress

**Comment by bhavya-sinha** [comment]
retrigger build

**Review by satyam-harness — DISMISSED** [review]

**Review by devinder-harness — DISMISSED** [review]

**Review by satyam-harness — APPROVED** [review]

**Review by devinder-harness — APPROVED** [review]

**Review by satyam-harness — APPROVED** [review]

**Comment by bhavya-sinha** [comment]
retrigger typecheck

**Review by samarth-sharma31 — APPROVED** [review]

**Pull request merged**
