### PR TITLE
fix: [LWG-1259]: days to be mandatory for periodic schedule

### PR DESCRIPTION
**Pull request by rishik30**
##### Summary:

Do not allow to submit the schedule form if no days are selected for a periodic schedule.

##### Screenshots:
Screenshot 2022-02-22 at 3 55 14 PM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by rishik30** [comment]
retrigger titlecheck

**Comment by rishik30** [comment]
retrigger typecheck

**Comment by rishik30** [comment]
retrigger jest

**Comment by rishik30** [comment]
trigger cypress

**Review by shalinlk — APPROVED** [review]

**Review by chrisblakely01 — APPROVED** [review]

**Pull request merged**
