### PR TITLE
fix: [CI-4486]: Update strings.en.yaml

### PR DESCRIPTION
**Pull request by rajatharanganath**
Changing noBuildText

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Review by vardanbansal-harness — APPROVED** [review]
Can we check if this is not being used in account context anywhere? If not, it looks good.

**Review by vardanbansal-harness — APPROVED** [review]

**Comment by rajatharanganath** [comment]
> Can we check if this is not being used in account context anywhere? If not, it looks good.

Used in Deployment/Build page only, and in case of CI we have CI specific message.

**Review by vardanbansal-harness — APPROVED** [review]

**Review by mtran7 — APPROVED** [review]

**Comment by rajatharanganath** [comment]
retrigger jest

**Comment by rajatharanganath** [comment]
un related flaky test failing.

**Pull request merged**
