### PR TITLE
feat: [PL-31439]: added polling (refetchInterval) to Streaming Destinations List Page

### PR DESCRIPTION
**Pull request by mayankVermaHarness**
### Summary
JIRA: https://harness.atlassian.net/browse/PL-31439
Added polling (refetchInterval) to Streaming Destinations List Page

**Test Details:**
Tested by keeping the polling interval as 5 seconds on local environment and saw that both `cards` and `aggregate list` API were auto-refetched every 5 seconds.
After testing, changed the interval to 10 minutes (as required by JIRA)

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by kapilkumawat86 — DISMISSED** [review]

**Review by udayvunnam — APPROVED** [review]
LGTM

**Comment by mayankVermaHarness** [comment]
retrigger titlecheck

**Comment by mayankVermaHarness** [comment]
retrigger cypress-rest

**Comment by mayankVermaHarness** [comment]
retrigger cypress-rest

**Comment by mayankVermaHarness** [comment]
retrigger cypress-pipeline

**Comment by mayankVermaHarness** [comment]
retrigger cypress-pipeline

**Comment by mayankVermaHarness** [comment]
retrigger cypress-rest

**Comment by mayankVermaHarness** [comment]
retrigger jest

**Review by udayvunnam — APPROVED** [review]

**Review by swarajcheguri-harness — APPROVED** [review]

**Pull request merged**
