### PR TITLE
feat: [CDS-34833]: RequiredFields will be rendered depending on issue…

### PR DESCRIPTION
**Pull request by goyalsonali**
…Type

##### Summary:

Jira Fields which are required for Jira create step will now be rendered when we choose an issueType. It will be required to fill before submitting the form.
Jira Fields which are optional will be the part of optional configuration only.

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by goyalsonali** [comment]
retrigger jest

**Comment by goyalsonali** [comment]
trigger cypress

**Review by kapilkumawat86 — DISMISSED** [review]

**Review by vkbansal — DISMISSED** [review]

**Comment by goyalsonali** [comment]
trigger cypress

**Comment by goyalsonali** [comment]
trigger cypress

**Comment by goyalsonali** [comment]
trigger cypress

**Comment by goyalsonali** [comment]
trigger cypress

**Comment by goyalsonali** [comment]
trigger cypress

**Comment by goyalsonali** [comment]
trigger rebase

**Pull request merged**
