### PR TITLE
fix: [CDS-43326]: added pdc connector validation

### PR DESCRIPTION
**Pull request by radujomir**
### Summary

Added validation for PDC connector

#### Screenshots
Screenshot 2022-10-27 at 19 06 50

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by radujomir** [comment]
retrigger titlecheck

**Comment by radujomir** [comment]
retrigger jest

**Comment by radujomir** [comment]
retrigger cypress-pipeline

**Comment by radujomir** [comment]
retrigger cypress-pipeline

**Comment by radujomir** [comment]
retrigger cypress-pipeline

**Comment by radujomir** [comment]
retrigger cypress-pipeline

**Comment by radujomir** [comment]
retrigger cypress-pipeline

**Comment by radujomir** [comment]
retrigger cypress-pipeline

**Review by avinashmadhwani02 — APPROVED** [review]

**Review by litvinovstas — APPROVED** [review]

**Pull request merged**
