### PR TITLE
feat: [PL-31104]: allow externally managed user deletion from org/project

### PR DESCRIPTION
**Pull request by tiwaritejas**
### Summary

An externally managed user deletion will be allowed from orgs and projects.

#### Screenshots
Screenshot 2023-01-26 at 11 10 17 AM

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by tiwaritejas** [comment]
retrigger titlecheck

**Comment by tiwaritejas** [comment]
retrigger coverage

**Comment by tiwaritejas** [comment]
retrigger jest

**Comment by tiwaritejas** [comment]
retrigger cypress-cd

**Comment by tiwaritejas** [comment]
retrigger jest

**Comment by tiwaritejas** [comment]
retrigger cypress-cv

**Comment by tiwaritejas** [comment]
retrigger jest, cypress-cd

**Comment by tiwaritejas** [comment]
retrigger jest

**Comment by tiwaritejas** [comment]
retrigger cypress-cd

**Comment by tiwaritejas** [comment]
retrigger coverage

**Comment by tiwaritejas** [comment]
retrigger jest

**Review by swarajcheguri-harness — APPROVED** [review]

**Review by reetika04 — DISMISSED** [review]

**Comment by tiwaritejas** [comment]
retrigger coverage

**Comment by tiwaritejas** [comment]
retrigger eslint

**Comment by tiwaritejas** [comment]
retrigger cypress-cv

**Comment by tiwaritejas** [comment]
retrigger cypress-cd

**Comment by tiwaritejas** [comment]
retrigger jest

**Comment by tiwaritejas** [comment]
retrigger jest

**Comment by tiwaritejas** [comment]
retrigger coverage

**Comment by tiwaritejas** [comment]
retrigger coverage

**Comment by tiwaritejas** [comment]
retrigger jest

**Review by mayankVermaHarness — APPROVED** [review]

**Comment by tiwaritejas** [comment]
retrigger jest

**Comment by tiwaritejas** [comment]
retrigger coverage

**Review by reetika04 — APPROVED** [review]

**Comment by tiwaritejas** [comment]
retrigger coverage

**Comment by tiwaritejas** [comment]
retrigger coverage

**Pull request merged**
