### PR TITLE
feat: [CDS-41479]: added azure infra for sshWinRm deployment type

### PR DESCRIPTION
**Pull request by vikrant-harness**
### Summary

added azure infra for sshWinRm deployment type

For Sonar Check :- The duplications are due to similar formik fields present in some another forms as well . 
For coverage :- Will update in the subsequent pr for coverage

#### Screenshots

https://user-images.githubusercontent.com/106532291/183393458-bf4ad7db-e56b-4ea0-a177-7c2da416f005.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 130 Issues 
* Code issue 130 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10409)

**Comment by vikrant-harness** [comment]
retrigger titlecheck

**Comment by vikrant-harness** [comment]
retrigger titlecheck

**Review by YounixIO — COMMENTED** [review]
Add Safety checks wherever possible and extract common functionality as discussed.

**Comment by vikrant-harness** [comment]
retrigger jest

**Review by YounixIO — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Review by YounixIO — APPROVED** [review]

**Review by Sagar-Rajput7 — APPROVED** [review]

**Review by vkbansal-harness — APPROVED** [review]

**Pull request merged**
