### PR TITLE
fix: [CDS-48917]: cluster list view changes -> adding agentIdentifier in the key

### PR DESCRIPTION
**Pull request by satyam-harness**
https://harness.atlassian.net/browse/CDS-47191
https://harness.atlassian.net/browse/CDS-48917
#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by satyam-harness** [comment]
retrigger jest

**Comment by satyam-harness** [comment]
retrigger titlecheck

**Review by ishantmehtaharness — APPROVED** [review]
Looks Good
We can merge post these 2 action Items
1. Confirm with @samarthwadhwa on UX
2. Update BE team to fix API

**Review by ishantmehtaharness — APPROVED** [review]

**Review by vkbansal-harness — APPROVED** [review]

**Comment by satyam-harness** [comment]
retrigger jest

**Pull request merged**
