### PR TITLE
fix: [PLG-1066]: Avoid stack dump when module name uppercase or not in table

### PR DESCRIPTION
**Pull request by chris-harness**
##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Review by nanaxuHarness — DISMISSED** [review]

**Comment by chris-harness** [comment]
trigger cypress

**Review by nanaxuHarness — APPROVED** [review]

**Comment by chris-harness** [comment]
trigger cypress

**Review by r0610205 — APPROVED** [review]

**Review by atmollo-harness — DISMISSED** [review]

**Comment by chris-harness** [comment]
trigger cypress

**Review by nanaxuHarness — APPROVED** [review]

**Review by atmollo-harness — DISMISSED** [review]

**Comment by chris-harness** [comment]
trigger cypress

**Comment by chris-harness** [comment]
trigger cypress

**Comment by chris-harness** [comment]
trigger cypress

**Comment by chris-harness** [comment]
retrigger jest

**Review by nanaxuHarness — APPROVED** [review]

**Review by nanaxuHarness — APPROVED** [review]

**Review by atmollo-harness — APPROVED** [review]

**Pull request merged**
