### PR TITLE
fix: [PIE-2904]: pre set fields getting reset in run pipeline form

### PR DESCRIPTION
**Pull request by AshwinBhatkal-Harness**
##### Summary:

When running selective stage in pipeline all the pre set fields are getting reset

##### Jira Links:

https://harness.atlassian.net/browse/PIE-2904

##### Screenshots:

Before:

https://user-images.githubusercontent.com/96711906/157394531-0353b1f1-743f-4319-8b4b-21fbb1c75edb.mov

After:

https://user-images.githubusercontent.com/96711906/157394538-d21a2ede-fc21-48ef-ac43-aa0cae3fee03.mov

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by AshwinBhatkal-Harness** [comment]
retrigger jest

**Comment by AshwinBhatkal-Harness** [comment]
trigger cypress

**Comment by AshwinBhatkal-Harness** [comment]
retrigger jest

**Comment by AshwinBhatkal-Harness** [comment]
trigger cypress

**Review by yc147 — APPROVED** [review]

**Review by dhruvUpadhyay07 — APPROVED** [review]

**Comment by AshwinBhatkal-Harness** [comment]
trigger cypress

**Review by kapilkumawat86 — APPROVED** [review]

**Review by vkbansal — APPROVED** [review]

**Pull request merged**
