### PR TITLE
feat: [FFM-2174]: updated tooltip text for FF plan enforcement

### PR DESCRIPTION
**Pull request by chrisblakely01**
##### Summary:

Updates the plan enforcement tooltip text to show the FF specific message when the user has reached their free plan limits

##### Jira Links:

https://harness.atlassian.net/browse/FFM-2174

##### Screenshots:

Screenshot 2022-01-25 at 14 47 51

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by chrisblakely01** [comment]
retrigger coverage

**Comment by chrisblakely01** [comment]
retrigger titlecheck

**Comment by chrisblakely01** [comment]
retrigger jest

**Review by crystal-fong — APPROVED** [review]
Looks good! 👍

**Review by kylekstewart — APPROVED** [review]

**Pull request merged**
