### PR TITLE
feat: [FFM-20872]: Fixing broken tests

### PR DESCRIPTION
**Pull request by chrisblakely01**
##### Summary:

Fixes broken Plan Enforcement tests. Related PR: https://github.com/harness/harness-core-ui/pull/6967

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by harshjain12** [comment]
retrigger coverage

**Comment by harshjain12** [comment]
trigger cypress

**Comment by chrisblakely01** [comment]
trigger cypress

**Review by crystal-fong — APPROVED** [review]

**Review by knagurski — APPROVED** [review]
Noice

**Pull request merged**
