### PR TITLE
feat: [CET-1185]: Adding Error Tracking Trial Page

### PR DESCRIPTION
**Pull request by cseverino789**
### Summary

- Adding Error Tracking trial page
- Updates to ET Home page
- Applies licensing data to RouteLayouts

#### Screenshots

Screen Shot 2023-04-24 at 4 56 36 PM

Screen Shot 2023-04-24 at 6 10 04 PM

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by David-Kreiner — APPROVED** [review]

**Comment by cseverino789** [comment]
retrigger eslint, cypress-rest, prettier, titlecheck, cypress-pipeline, cypress-cv

**Comment by cseverino789** [comment]
retrigger titlecheck

**Comment by cseverino789** [comment]
retrigger  cypress-pipeline, cypress-cv, cypress-rest

**Comment by cseverino789** [comment]
retrigger prettier cypress-cv

**Review by ricksjames — APPROVED** [review]

**Comment by cseverino789** [comment]
retrigger eslint

**Comment by cseverino789** [comment]
retrigger typecheck

**Review by tan-nhu — APPROVED** [review]

**Review by jsentongo — APPROVED** [review]

**Comment by cseverino789** [comment]
retrigger jest

**Comment by cseverino789** [comment]
retrigger cypress-pipeline

**Pull request merged**
