### PR TITLE
fix: [CDS-36235]: add cypress test case and make stages optional field

### PR DESCRIPTION
**Pull request by chetanvekariya-harness**
##### Summary:
- Add cypress test case for a use-case when artifactPath and artifactPathFilter both are not given and error appears before when Save button is clicked
- Make stages optional field to getStepPaletteModuleInfosFromStage function

##### Jira Links:
https://harness.atlassian.net/browse/CDS-36235

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Comment by chetanvekariya-harness** [comment]
trigger cypress

**Comment by chetanvekariya-harness** [comment]
trigger cypress

**Review by AshwinBhatkal-Harness — APPROVED** [review]

**Pull request merged**
