### PR TITLE
fix: [PIE-3161]: fix notification flaky test

### PR DESCRIPTION
**Pull request by samarth-sharma31**
##### Summary:

**Auto scroll behaviour of cypress causes the content to shift upwards, hiding it from the modal and as a result it hides the dom node. Have disabled to auto scrolling behaviour for this particular flaky test.**

Screenshot 2022-03-17 at 3 49 20 PM

##### Jira Links:

https://harness.atlassian.net/browse/PIE-3161

##### Screenshots:

Screenshot 2022-03-17 at 5 54 38 PM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by samarth-sharma31** [comment]
trigger cypress

**Comment by samarth-sharma31** [comment]
trigger cypress

**Comment by samarth-sharma31** [comment]
trigger cypress

**Comment by samarth-sharma31** [comment]
trigger cypress

**Review by kapilkumawat86 — APPROVED** [review]

**Review by PratyushGar — APPROVED** [review]

**Pull request merged**
