### PR TITLE
fix: [PIE-5378]: UI Changes needed for Artifact and Manifest triggers also show as Webhook in the triggered by information

### PR DESCRIPTION
**Pull request by pankajsingh-harness**
#### Screenshots
Screenshot 2022-10-07 at 9 05 32 AM
Screenshot 2022-10-07 at 9 13 17 AM

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11614)

**Comment by pankajsingh-harness** [comment]
retrigger titlecheck

**Comment by pankajsingh-harness** [comment]
trigger cypress

**Review by depanshu-dhiman — APPROVED** [review]

**Comment by pankajsingh-harness** [comment]
trigger cypress

**Comment by pankajsingh-harness** [comment]
trigger cypress

**Comment by pankajsingh-harness** [comment]
trigger cypress

**Review by vkbansal-harness — APPROVED** [review]

**Pull request merged**
