### PR TITLE
fix: [CI-5810]: Removed non-compatible os and arch options for CIE_HOSTED_VMS

### PR DESCRIPTION
**Pull request by shaurya-harness**
### Summary

Removed non-compatible os and arch options for CIE_HOSTED_VMS

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by shaurya-harness** [comment]
retirgger titlecheck

**Comment by shaurya-harness** [comment]
retrigger titlecheck

**Comment by shaurya-harness** [comment]
trigger cypress

**Review by d1wilko — APPROVED** [review]
LGTM

**Comment by shaurya-harness** [comment]
trigger cypress

**Review by mtran7 — APPROVED** [review]

**Pull request merged**
