### PR TITLE
feat: [PIE-2794]: acr and azure infra

### PR DESCRIPTION
**Pull request by Tamaraius**
##### Summary:
ACR and Azure infrastructure implementation

##### Jira Links:
https://harness.atlassian.net/browse/PIE-2794
https://harness.atlassian.net/browse/PIE-2791

##### Screenshots:
ACR
https://user-images.githubusercontent.com/96610348/166709062-5a5315c6-4978-4310-a453-d96fb22e2ade.mov

Azure Infra
https://user-images.githubusercontent.com/96610348/166709079-56324d08-f46c-4c81-88df-e0cbf421122d.mov

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by Tamaraius** [comment]
retrigger titlecheck

**Comment by Tamaraius** [comment]
retrigger coverage

**Comment by Tamaraius** [comment]
retrigger typecheck

**Comment by Tamaraius** [comment]
trigger cypress

**Review by harshilbits — APPROVED** [review]

**Review by bhavya-sinha — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
