### PR TITLE
fix: [SRM-12247]: Policies (Harness Policy Engine) tab is always bein…

### PR DESCRIPTION
**Pull request by vasuki-kalluri**
…g displayed in SRM module

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by vardanbansal-harness — DISMISSED** [review]

**Review by kylekstewart — APPROVED** [review]

**Review by avinashmadhwani02 — DISMISSED** [review]

**Review by kylekstewart — DISMISSED** [review]

**Comment by vasuki-kalluri** [comment]
retrigger coverage

**Comment by vasuki-kalluri** [comment]
retrigger coverage

**Comment by vasuki-kalluri** [comment]
retrigger jest

**Review by avinashmadhwani02 — APPROVED** [review]
Please create a ticket to remove comment from the test case

**Review by kylekstewart — APPROVED** [review]

**Comment by vasuki-kalluri** [comment]
trigger cypress

**Comment by vasuki-kalluri** [comment]
trigger cypress

**Review by mtran7 — APPROVED** [review]

**Pull request merged**
