### PR TITLE
feat: [FFM-3022]: Targeting Rule Ordering & Reordering, tests and refactoring

### PR DESCRIPTION
**Pull request by chrisblakely01**
##### Summary:

- Allows users to reprioritise rules by deleting/re-adding them
- Refactoring and code tidy up

##### Video:

https://user-images.githubusercontent.com/10871707/164706291-979af983-671d-4d78-99af-c6a220cd626a.mov

Screenshot 2022-04-22 at 12 33 13

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by chrisblakely01** [comment]
retrigger jest

**Comment by chrisblakely01** [comment]
trigger cypress

**Comment by chrisblakely01** [comment]
trigger cypress

**Comment by chrisblakely01** [comment]
trigger cypress

**Comment by chrisblakely01** [comment]
retrigger jest

**Comment by chrisblakely01** [comment]
trigger cypress

**Review by kylekstewart — APPROVED** [review]

**Review by laura-mannus — APPROVED** [review]
Really nice work :)

**Pull request merged**
