### PR TITLE
fix: [CDS-49708]: Jenkins step change confirmation dialog when no changes

### PR DESCRIPTION
**Pull request by pankajsingh-harness**
### Summary

This PR has generic fix for all the Pipeline Steps _**Change Confirmation Dialog without any interaction issue in PipelineStepFactory**._ 

Existing implementation was based on the formikProps.dirty which compares formik initialValues and current values.

[Formik.tsx](https://github.com/jaredpalmer/formik/blob/master/packages/formik/src/Formik.tsx#L933)
```
const dirty = React.useMemo(
    () => !isEqual(initialValues.current, state.values),
    [initialValues.current, state.values]
  );
```
We sometime update formik state in some API response or with some side effect without user interaction. So user was getting the Change Confirmation Dialog without any interaction. 

With this change we are using the **processFormData** method from the **PipelineStep** to process initialValues and current values and then compare the values for change. 

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by sonaligoyal-harness — APPROVED** [review]

**Comment by pankajsingh-harness** [comment]
retrigger titlecheck

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cv

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Comment by pankajsingh-harness** [comment]
Coverage failing only

Screenshot 2023-04-05 at 3 26 24 PM

**Pull request merged**
