### PR TITLE
fix: [CODE-1198]:  icons in new nav

### PR DESCRIPTION
**Pull request by rkapoor10**
### Summary

- added icons for repositories and search in CODE nav
-  updated nav icon styles for CODE

#### Screen Recording

https://github.com/harness/harness-core-ui/assets/61417822/a762f2d7-0aa2-4700-be2f-95b93d08f6b6

#### Screenshots

- new icons 
  - expanded
  
Screenshot 2023-12-19 at 7 34 54 PM

  - collapsed
  
Screenshot 2023-12-19 at 7 35 17 PM

  
- nav indentation fix
  - expanded
  Screenshot 2023-12-19 at 7 35 35 PM

  - collapsed
Screenshot 2023-12-19 at 7 35 27 PM

### CODE REVIEW

**Review by tan-nhu — APPROVED** [review]

**Comment by tan-nhu** [comment]
Code looks good to me. Our current icons are not well standardized so we have to do this way, unfortunately.

**Comment by rkapoor10** [comment]
trigger smartchecks

**Comment by rkapoor10** [comment]
retrigger jest
retrigger prettier
retrigger typecheck
retrigger sonar
retrigger standards
retrigger build
trigger featurenamecheck
retrigger coverage
retrigger cypress-rest
retrigger cypress-cd
retrigger cypress-pipeline
retrigger cypress-cv
trigger messagecheck

**Comment by rkapoor10** [comment]
retrigger jest

**Comment by rkapoor10** [comment]
trigger messagecheck

**Comment by rkapoor10** [comment]
retrigger standards

**Comment by rkapoor10** [comment]
retrigger messagecheck

**Comment by rkapoor10** [comment]
retrigger coverage

**Pull request merged**
