### PR TITLE
fix: [PL-27579]: Git simplification fixes for handling unexpected pipelines entries

### PR DESCRIPTION
**Pull request by sunnykesh-harness**
### Summary

Changes are 
1. We had observed something went wrong for pipeline list page.
RCA: 
[Project has old gitSync enabled](https://qa.harness.io/ng/#/account/px7xd_BFRCi-pfWPYXVjvw/cd/orgs/deafult/projects/AmitTest/pipelines) but so UI is expecting gitDetails for all the pipelines (repoIdentifier, branch).
 But response has  one of pipeline (p2 - clone) as Inline   which should not be.
It was created by cloning  pipeline was saved as Inline .  So, adding some null check to handle these unexpected entries but these pipelines may not work E2E as  it was supposed to be in Git with old gitSync.

2. Minor Git simplification fixes for gitSyncEnabledOnlyForFF use case
3. Cherry picking : https://github.com/harness/harness-core-ui/pull/10671/files changes

#### Screenshots
Screenshot 2022-08-23 at 1 09 27 PM

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10714)

**Comment by sunnykesh-harness** [comment]
retrigger titlecheck

**Review by udayvunnam — DISMISSED** [review]

**Comment by sunnykesh-harness** [comment]
retrigger titlecheck

**Review by vkbansal-harness — DISMISSED** [review]

**Review by upadhyay-an — DISMISSED** [review]

**Review by vkbansal-harness — APPROVED** [review]

**Review by mayankVermaHarness — APPROVED** [review]

**Comment by sunnykesh-harness** [comment]
retrigger coverage

**Comment by sunnykesh-harness** [comment]
retrigger jest

**Pull request merged**
