### PR TITLE
fix: [CDB-139]: Fix for opening new Dashboard tab through context menu

### PR DESCRIPTION
**Pull request by Harness-JKhattak**
##### Summary:

- Fixed an issue on our environments where opening a Dashboard in a new tab through the context menu was failing due to the base URL not including next gen path.

##### Jira Links:

[CDB-139](https://harness.atlassian.net/browse/CDB-139)

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by Harness-JKhattak** [comment]
trigger cypress

**Comment by sean-harness** [comment]
trigger cypress

**Review by sean-harness — APPROVED** [review]

**Comment by Harness-JKhattak** [comment]
trigger cypress

**Review by willd0yle — DISMISSED** [review]

**Review by chrisblakely01 — DISMISSED** [review]

**Comment by Harness-JKhattak** [comment]
trigger cypress

**Review by sean-harness — APPROVED** [review]

**Review by knagurski — APPROVED** [review]
Looks good 👍

**Pull request merged**
