### PR TITLE
feat: [CDS-85657] Service creation modal scroll should not include footer button

### PR DESCRIPTION
**Pull request by kanikamittal09**
### Summary

This PR contains fix for:

- [Service creation modal scroll should not include footer button](https://harness.atlassian.net/browse/CDS-85657): Made  only form content to scroll in NewEditServiceForm
- [Remove backward compatibility changes made in PR https://github.com/harness/harness-core-ui/pull/18753](https://harness.atlassian.net/browse/CDS-83389): Removed PageSpinner from NewEditServiceModal.tsx

#### Screenshots

- Existing Behaviour

https://github.com/harness/harness-core-ui/assets/94995410/53b4f765-2569-44e1-84fe-d45eca55834a

- Updated 

https://github.com/harness/harness-core-ui/assets/94995410/1d69bc50-f483-4d92-abe8-9ecb37d9add2

#### Manual Testing
- Tested Service Creation for inline and remote
- Checked field validations 
- Tested Service Creation for inline and remote from service dashboard
NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

### CODE REVIEW

**Comment by kanikamittal09** [comment]
retrigger jest

**Comment by kanikamittal09** [comment]
retrigger coverage

**Comment by kanikamittal09** [comment]
trigger messagecheck

**Review by pankajsingh-harness — APPROVED** [review]

**Review by litvinovstas — APPROVED** [review]

**Comment by kanikamittal09** [comment]
Coverage ticket https://harness.atlassian.net/browse/CDS-87100

**Review by ishantmehtaharness — APPROVED** [review]
this is used in Gitops too, please see if its working fine there too

**Comment by kanikamittal09** [comment]
@ishantmehtaharness i see there is some issue in qa itself 

https://github.com/harness/harness-core-ui/assets/94995410/948aaa4b-0423-4574-80d0-d9422f6fe3ce

same behaviour is in this branch


https://github.com/harness/harness-core-ui/assets/94995410/af68611a-13fd-4121-97ff-4e8f317df1f9

i'm not sure if NewEditServiceModal is being used here
Can you pls check and tell exactly where this component is being used in gitops

**Comment by ishantmehtaharness** [comment]
> @ishantmehtaharness i see there is some issue in qa itself 
> 
> 
> 
> https://github.com/harness/harness-core-ui/assets/94995410/948aaa4b-0423-4574-80d0-d9422f6fe3ce
> 
> 
> 
> same behaviour is in this branch
> 
> 
> 
> 
> 
> https://github.com/harness/harness-core-ui/assets/94995410/af68611a-13fd-4121-97ff-4e8f317df1f9
> 
> 
> 
> i'm not sure if NewEditServiceModal is being used here
> 
> Can you pls check and tell exactly where this component is being used in gitops
> 
> 

@pankajsingh-harness @sahithikolichala could you please help on this ine

**Comment by kanikamittal09** [comment]
The gitops issue is separate and not caused by changes in this pr 
gitops pr : https://github.com/wings-software/gitops/pull/2602

**Comment by pankajsingh-harness** [comment]
@ishantmehtaharness the issue reported is an existing issue not related to this fix. I have raised PR for this fix in gitops: https://github.com/wings-software/gitops/pull/2602. @sahithikolichala Please verify the changes and get the OR merged.

**Pull request merged**
