### PR TITLE
feat: [CDS-38808]: Azure Slot Deployment step

### PR DESCRIPTION
**Pull request by Tamaraius**
##### Summary:
Azure Slot Deployment step

##### Jira Links:
https://harness.atlassian.net/browse/CDS-38808

##### Screenshots:
https://user-images.githubusercontent.com/96610348/174073430-7e5432bd-4f5d-4e70-94e8-a47a46a37a53.mov

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by Tamaraius** [comment]
retrigger coverage

**Comment by Tamaraius** [comment]
retrigger coverage

**Comment by Tamaraius** [comment]
retrigger coverage

**Comment by Tamaraius** [comment]
retrigger jest

**Comment by Tamaraius** [comment]
trigger rebase

**Comment by Tamaraius** [comment]
retrigger coverage

**Review by satyam-harness — APPROVED** [review]

**Review by azharness — APPROVED** [review]

**Pull request merged**
