### PR TITLE
fix: [PIE-2147]: Changed empty state images of pipelines

### PR DESCRIPTION
**Pull request by goyalsonali**
Summary:

Updated the pipeline empty states image for each applicable module

Jira Links:

https://harness.atlassian.net/browse/PIE-2147

Screenshots:

Screenshot 2022-02-16 at 5 53 39 PM
Screenshot 2022-02-16 at 5 53 31 PM
Screenshot 2022-02-16 at 5 53 25 PM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by goyalsonali** [comment]
retrigger titlecheck

**Comment by goyalsonali** [comment]
retrigger titlecheck

**Comment by goyalsonali** [comment]
retrigger coverage

**Comment by goyalsonali** [comment]
retrigger titlecheck

**Comment by goyalsonali** [comment]
retrigger coverage

**Comment by goyalsonali** [comment]
retrigger coverage

**Review by bhavya-sinha — CHANGES_REQUESTED** [review]

**Comment by goyalsonali** [comment]
retrigger jest

**Pull request closed without merging**
