### PR TITLE
fix: [CDS-82459]: removed race condition in formik update in jiraUpdate step

### PR DESCRIPTION
**Pull request by satyam-harness**
### Summary
Problem - Upon changing transition, we have to update status. Due to 2 parallel `formik.updateValue` running, sometime it returns inappropriate result. 

Solution -  Removed race condition by using produce.

Manual test - 

- Checked if formikValue is getting updated properly.
- Checked if validations are running properly for transitions and status.
- Checked upon making transition runtime/expression, status should not be changed. 

#### Screenshots
Before - 

https://github.com/harness/harness-core-ui/assets/96036463/b63eb81f-5f5e-497c-b66a-f1c3b9709116

After - 

https://github.com/harness/harness-core-ui/assets/96036463/a0b93c73-e69a-4c95-97f0-b877d46e322b

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

### CODE REVIEW

**Comment by satyam-harness** [comment]
retrigger jest

**Comment by satyam-harness** [comment]
trigger messagecheck

**Comment by satyam-harness** [comment]
trigger messagecheck

**Comment by satyam-harness** [comment]
trigger messagecheck

**Review by chetanvekariya-harness — APPROVED** [review]

**Review by rameshx — APPROVED** [review]

**Pull request merged**
