### PR TITLE
feat: [SMP-1966]: added common annotations and labels

### PR DESCRIPTION
**Pull request by avaakash**
### Summary

This PR adds the option to add common annotations and labels to all the chart resources. There is a requirement to annotate or label all the services to work with certain cloud provider settings, currently, the process is tedious which is adding annotations to each of the services separately. With this PR, it can be added as a global override to all the charts.

### Testing
I have tested the changes by doing helm template with different configuration combinations and the charts template without any error.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by avaakash** [comment]
retrigger titlecheck

**Comment by avaakash** [comment]
retrigger titlecheck

**Comment by avaakash** [comment]
retrigger titlecheck

**Review by akshay-khole — DISMISSED** [review]

**Comment by avaakash** [comment]
trigger titlecheck

**Comment by avaakash** [comment]
retrigger jest

**Review by arya-harness — APPROVED** [review]

**Review by akshay-khole — APPROVED** [review]

**Pull request merged**
