### PR TITLE
feat: [CDS-35062]: Ssh infra implementation

### PR DESCRIPTION
**Pull request by azharness**
* feat: [CDS-35062]: merge ssh wizard creation

* feat: [CDS-35062]: pdc infra update

* feat: [CDS-35062]: fix cypress

* feat: [CDS-35062]: fix tests

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

[CDS-35062]: https://harness.atlassian.net/browse/CDS-35062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-35062]: https://harness.atlassian.net/browse/CDS-35062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-35062]: https://harness.atlassian.net/browse/CDS-35062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CDS-35062]: https://harness.atlassian.net/browse/CDS-35062?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by azharness** [comment]
retrigger titlecheck

**Comment by azharness** [comment]
retrigger coverage

**Comment by azharness** [comment]
trigger cypress

**Comment by azharness** [comment]
retrigger coverage

**Comment by azharness** [comment]
retrigger jest

**Comment by azharness** [comment]
trigger rebase

**Comment by azharness** [comment]
retrigger jest

**Comment by azharness** [comment]
retrigger coverage

**Comment by azharness** [comment]
retrigger jest

**Comment by azharness** [comment]
retrigger coverage

**Comment by azharness** [comment]
retrigger coverage

**Review by Tamaraius — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
