### PR TITLE
fix: [SRM-10569]: Fix SLO page bugs

### PR DESCRIPTION
**Pull request by praneshg239**
##### Jira Links:

This PR contains fix for SRM-10569, SRM-10570, SRM-10601
##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Review by vasuki-kalluri — APPROVED** [review]

**Comment by praneshg239** [comment]
retrigger titlecheck

**Comment by praneshg239** [comment]
retrigger titlecheck

**Comment by praneshg239** [comment]
retrigger titlecheck

**Review by deepesh-ui — DISMISSED** [review]

**Review by deepesh-ui — APPROVED** [review]

**Review by vasuki-kalluri — APPROVED** [review]

**Comment by praneshg239** [comment]
retrigger jest

**Comment by praneshg239** [comment]
retrigger titlecheck

**Comment by praneshg239** [comment]
trigger cypress

**Pull request merged**
