### PR TITLE
feat: [PL-22339]: Separate CSS chunk entry in index.html

### PR DESCRIPTION
**Pull request by mayankVermaHarness**
##### Summary:

Part of build improvements. Adds a separate CSS chunk entry in index.html.
We currently don't have CSS entry in index.html as a part of our build process
So CSS loads only after all JS has downloaded, parsed & executed.
This change will add an entry of css in index.html that will ensure that styles load fast because now they'll load in parallel to JS.

##### Jira Links:

https://harness.atlassian.net/browse/PL-22339

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Review by abhinavrastogi-harness — DISMISSED** [review]

**Comment by mayankVermaHarness** [comment]
trigger cypress

**Comment by mayankVermaHarness** [comment]
trigger cypress

**Comment by mtran7** [comment]
retrigger jest

**Comment by mtran7** [comment]
trigger cypress

**Comment by mayankVermaHarness** [comment]
trigger rebase

**Comment by mayankVermaHarness** [comment]
trigger rebase

**Comment by mayankVermaHarness** [comment]
retrigger titlecheck

**Comment by mayankVermaHarness** [comment]
retrigger typecheck

**Comment by mayankVermaHarness** [comment]
trigger cypress

**Review by avinashmadhwani02 — APPROVED** [review]

**Pull request merged**
