### PR TITLE
feat: [CDS-34638]: added env label for environment dropdown

### PR DESCRIPTION
**Pull request by cjlee01**
##### Summary:

added custom env label for environment dropdown

##### Jira Links:

https://harness.atlassian.net/browse/CDS-34638

##### Screenshots:

image

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by cjlee01** [comment]
retrigger titlecheck

**Comment by cjlee01** [comment]
retrigger titlecheck

**Comment by cjlee1** [comment]
retrigger sonar

**Comment by cjlee1** [comment]
retrigger sonarqube

**Review by bhavya-sinha — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Review by vkbansal — APPROVED** [review]

**Pull request merged**
