### PR TITLE
feat: [FFM-5391]: remove additional step added to FF Onboarding flow

### PR DESCRIPTION
**Pull request by Kira-Jennings**
### Summary

Step was added for Set Up Your Code (readme), undo this and put content back under SDK Key creation in step 2
JIRA: https://harness.atlassian.net/browse/FFM-5391

- put content back in SetUpYourApplicationView
- remove step from stepper at top of page
- update unit tests

#### Screenshots
image

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by laura-mannus** [comment]
The final step is now unaligned, as well as the complete/back buttons 
image

**Comment by laura-mannus** [comment]
Coverage is now failing on this, I have a ticket open to improve these tests https://harness.atlassian.net/browse/FFM-5377 however it was passing initially so not sure what happened?

**Comment by Kira-Jennings** [comment]
@laura-mannus fixed the padding issue. I don't know what's wrong with the coverage as I actually removed code in this PR so surely it should have gone up? lol I'll work on it now
image

**Review by laura-mannus — APPROVED** [review]
Looks good :)

**Review by crystal-fong — APPROVED** [review]

**Pull request merged**
