### PR TITLE
fix: [PL-24072]: Replacing generic error message to RBAC Error Message

### PR DESCRIPTION
**Pull request by reetika04**
##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by reetika04** [comment]
retrigger titlecheck

**Review by abhinavrastogi-harness — DISMISSED** [review]

**Comment by reetika04** [comment]
Screenshot 2022-03-29 at 5 56 17 PM

**Review by abhinavrastogi-harness — DISMISSED** [review]

**Comment by reetika04** [comment]
retrigger rebase

**Review by mayankVermaHarness — DISMISSED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Review by rishik30 — DISMISSED** [review]

**Comment by reetika04** [comment]
trigger cypress

**Review by desagnik — DISMISSED** [review]
Looks fine for the changes to the files owned by my team.

**Comment by reetika04** [comment]
trigger cypress

**Review by chetanvekariya-harness — APPROVED** [review]

**Comment by reetika04** [comment]
trigger rebase

**Review by rishik30 — DISMISSED** [review]

**Review by kapilkumawat86 — DISMISSED** [review]

**Review by harshilbits — APPROVED** [review]

**Review by desagnik — DISMISSED** [review]

**Comment by abhinavrastogi-harness** [comment]
force-merging to avoid more conflicts. already approved before rebase.

**Pull request merged**
