### PR TITLE
feat: [PIE-4967]: triggers shown with appropriate icon and links in pipelines

### PR DESCRIPTION
**Pull request by udayvunnam**
### Summary

- triggers(cron and webhook) are shown with appropriate icons and added links to navigate to the trigger in the pipeline list view
- arrow icon for the latest execution indicator
- view executions nav link fix

Also includes commits from https://github.com/harness/harness-core-ui/pull/10656 included @vikrant-harness 

#### Screenshots

image

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [x] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by vikrant-harness — APPROVED** [review]

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 10 Issues 
* Code issue 10 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10670)

**Review by rameshx — APPROVED** [review]

**Review by Sagar-Rajput7 — APPROVED** [review]

**Comment by udayvunnam** [comment]
retrigger jest

**Comment by udayvunnam** [comment]
retrigger jest

**Comment by vikrant-harness** [comment]
retrigger jest

**Review by vikrant-harness — APPROVED** [review]

**Review by Sagar-Rajput7 — APPROVED** [review]

**Review by vkbansal-harness — APPROVED** [review]

**Pull request merged**
