### PR TITLE
fix: [CHAOS-1145]: Chaos.svg change along with doc link updates and minor fixes

### PR DESCRIPTION
**Pull request by S-ayanide**
### Summary

Changes
* Chaos.svg change 
* Developer doc link redirection updated
* defaultTo updated to useParams

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by hrishavjha — APPROVED** [review]

**Review by vanshBhatia-A4k9 — DISMISSED** [review]

**Review by SahilKr24 — APPROVED** [review]
please run the svg through https://jakearchibald.github.io/svgomg/ once

**Review by arkajyotiMukherjee — CHANGES_REQUESTED** [review]
svg needs minification. Rest looks good.

**Review by arkajyotiMukherjee — APPROVED** [review]

**Review by hrishavjha — DISMISSED** [review]

**Comment by ajeshbaby** [comment]
Can we get this merged? @abhinavrastogi-harness

**Comment by SahilKr24** [comment]
retrigger cypress-cd

**Review by hrishavjha — APPROVED** [review]

**Pull request merged**
