### PR TITLE
fix: [CDS-36319]: removing redundancy in variable view for timeout an…

### PR DESCRIPTION
**Pull request by samarth-sharma31**
…d name fields

##### Summary:

Removes name and timeout field at step level to ensure they are not rendered redundantly

##### Screenshots:

Before -->

Screenshot 2022-06-16 at 2 04 34 PM

After ->

Screenshot 2022-06-16 at 5 37 54 PM
Screenshot 2022-06-16 at 5 38 58 PM
Screenshot 2022-06-16 at 5 40 24 PM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by samarth-sharma31** [comment]
trigger cypress

**Review by kapilkumawat86 — APPROVED** [review]

**Review by goyalsonali — APPROVED** [review]

**Comment by samarth-sharma31** [comment]
trigger rebase

**Comment by samarth-sharma31** [comment]
trigger cypress

**Comment by samarth-sharma31** [comment]
trigger cypress

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
