### PR TITLE
fix: [CDS-53878]: Disabled Nexus Version for inline connector creating in trigger and artifact

### PR DESCRIPTION
**Pull request by pankajsingh-harness**
### Summary
This PR also contains fix for the wrong version getting populated for the Nexus Version Connector in Edit mode which was release blocker due to regression caused by [https://harness.atlassian.net/browse/CDS-53308](https://harness.atlassian.net/browse/CDS-53308) fix.

#### Screenshots
Before:

https://user-images.githubusercontent.com/110591046/220367199-95dac247-23d9-4113-9241-7340cf666dd6.mov

After:

https://user-images.githubusercontent.com/110591046/220367282-ca5123e6-90ec-442a-8a63-46c39c24066b.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by pankajsingh-harness** [comment]
retrigger jest

**Comment by pankajsingh-harness** [comment]
retrigger jest

**Comment by pankajsingh-harness** [comment]
retrigger jest

**Comment by pankajsingh-harness** [comment]
retrigger jest

**Comment by pankajsingh-harness** [comment]
retrigger jest

**Review by AshwinBhatkal-Harness — APPROVED** [review]

**Review by samarth-sharma31 — APPROVED** [review]

**Comment by pankajsingh-harness** [comment]
retrigger jest

**Comment by pankajsingh-harness** [comment]
retrigger jest

**Review by vkbansal-harness — APPROVED** [review]

**Comment by pankajsingh-harness** [comment]
retrigger jest

**Comment by pankajsingh-harness** [comment]
retrigger coverage

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Review by samarth-sharma31 — APPROVED** [review]

**Review by AshwinBhatkal-Harness — APPROVED** [review]

**Review by sunnykesh-harness — APPROVED** [review]

**Pull request merged**
