### PR TITLE
feat: [CDS-41424]: Added skip rendering

### PR DESCRIPTION
**Pull request by sonaligoyal-harness**
#### Screenshots

https://user-images.githubusercontent.com/98508399/184097440-13c230c8-3f04-4e48-8bfc-e7efb8bdb17a.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 7 Issues 
* Code issue 7 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10535)

**Comment by sonaligoyal-harness** [comment]
retrigger jest

**Comment by sonaligoyal-harness** [comment]
trigger rebase

**Review by Sagar-Rajput7 — APPROVED** [review]
looks good

**Comment by sonaligoyal-harness** [comment]
retrigger jest

**Review by rameshx — APPROVED** [review]

**Pull request merged**
