### PR TITLE
fix: [CDS-69872]: Refresh token OIDC support for service now connector

### PR DESCRIPTION
**Pull request by samarth-sharma31**
### Summary

Tech spec link -> https://harness.atlassian.net/wiki/spaces/CDNG/pages/21386658285/Tech+Spec+ServiceNow+refresh+token+Oauth+support

Test cases link --> https://docs.google.com/spreadsheets/d/1hnPxaVVSAMviqdyyZx_FwHGzcdNEKSynCNcvJ3bYano/edit#gid=0

#### Screenshots

Screenshot 2023-06-13 at 1 41 51 PM
Screenshot 2023-06-13 at 1 46 25 PM
Screenshot 2023-06-13 at 1 47 01 PM

https://github.com/harness/harness-core-ui/assets/96409598/9fe1af1e-a46a-44de-b068-8a010b8af472

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by rameshx — APPROVED** [review]

**Review by chetanvekariya-harness — APPROVED** [review]

**Comment by samarth-sharma31** [comment]
retrigger build

**Comment by samarth-sharma31** [comment]
retrigger eslint

**Comment by samarth-sharma31** [comment]
retrigger jest

**Comment by samarth-sharma31** [comment]
retrigger prettier

**Comment by samarth-sharma31** [comment]
retrigger prettier

**Comment by samarth-sharma31** [comment]
retrigger coverage

**Comment by samarth-sharma31** [comment]
retrigger titlecheck

**Comment by samarth-sharma31** [comment]
trigger featurenamecheck

**Comment by samarth-sharma31** [comment]
retrigger standards

**Comment by samarth-sharma31** [comment]
retrigger typecheck

**Comment by samarth-sharma31** [comment]
retrigger typecheck

**Comment by samarth-sharma31** [comment]
retrigger typecheck

**Review by swarajcheguri-harness — APPROVED** [review]

**Pull request merged**
