### PR TITLE
fix: [PL-25012]: Remove the lower case for error message in yaml builder

### PR DESCRIPTION
**Pull request by DeepakPatankar**
…ard coded to lower letter

##### Summary:

The error message was always truncated to lower case letters. But this also results in giving the wrong suggestion as the `identifier` is also converted to a lower case letter. 

##### Jira Links:

https://harness.atlassian.net/browse/PL-25012

##### Screenshots:

Screenshot 2022-06-16 at 4 50 29 PM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Review by meenakshi-harness — APPROVED** [review]

**Comment by DeepakPatankar** [comment]
retrigger titlecheck

**Comment by DeepakPatankar** [comment]
retrigger titlecheck

**Comment by DeepakPatankar** [comment]
retrigger titlecheck

**Comment by DeepakPatankar** [comment]
retrigger titlecheck

**Review by mitishapandey — APPROVED** [review]

**Comment by DeepakPatankar** [comment]
retrigger titlecheck

**Comment by DeepakPatankar** [comment]
retrigger titlecheck

**Comment by DeepakPatankar** [comment]
retrigger titlecheck

**Pull request merged**
