### PR TITLE
feat: [CCM-7195]: Support for Instance groups in GCP 

### PR DESCRIPTION
**Pull request by rishik30**
##### Screenshots:
Screenshot 2022-04-06 at 5 14 09 PM
Screenshot 2022-04-06 at 5 13 53 PM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by rishik30** [comment]
trigger sonar

**Comment by rishik30** [comment]
retrigger sonar

**Comment by rishik30** [comment]
retrigger sonar

**Comment by rishik30** [comment]
retrigger jest

**Comment by rishik30** [comment]
retrigger sonar

**Review by jenil-harness — APPROVED** [review]

**Comment by rishik30** [comment]
retrigger sonar

**Pull request closed without merging**
