### PR TITLE
fix: [CDS-34964]: repositioned credentials Ref and added `${name}:${id}` in subscription ID dropdown

### PR DESCRIPTION
**Pull request by vikrant-harness**
### Summary

repositioned credentials Ref and added `name+id` in subscription ID dropdown

#### Screenshots

https://user-images.githubusercontent.com/106532291/189471429-a02543c9-de57-4871-879e-3f674b03357a.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 3 Issues 
* Code issue 3 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11163)

**Comment by vikrant-harness** [comment]
retrigger titlecheck

**Comment by vikrant-harness** [comment]
trigger cypress

**Comment by vikrant-harness** [comment]
trigger cypress

**Comment by vikrant-harness** [comment]
retrigger jest

**Pull request closed without merging**
