### PR TITLE
fix: [CDS-67696]: adding skip toggle for step and stage nodes (#16003)

### PR DESCRIPTION
**Pull request by satyam-harness**
* fix: [CDS-67696]: adding skip toggle for step and stage nodes

* fix: added toggle in stepgroup nodealso

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[CDS-67696]: https://harness.atlassian.net/browse/CDS-67696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by satyam-harness** [comment]
retrigger cypress-rest

**Comment by satyam-harness** [comment]
retrigger cypress-cd

**Comment by satyam-harness** [comment]
retrigger cypress-pipeline

**Comment by satyam-harness** [comment]
retrigger cypress-cv

**Comment by satyam-harness** [comment]
retrigger cypress-cd

**Comment by satyam-harness** [comment]
retrigger cypress-rest

**Review by AshwinBhatkal-Harness — APPROVED** [review]

**Comment by satyam-harness** [comment]
retrigger cypress-cv

**Comment by satyam-harness** [comment]
retrigger cypress-cd

**Comment by satyam-harness** [comment]
retrigger cypress-rest

**Comment by satyam-harness** [comment]
retrigger cypress-pipeline

**Comment by satyam-harness** [comment]
retrigger cypress-cv

**Review by vikrant-harness — APPROVED** [review]

**Comment by satyam-harness** [comment]
retrigger cypress-cv
retrigger cypress-pipeline

**Comment by satyam-harness** [comment]
retrigger cypress-pipeline

**Comment by satyam-harness** [comment]
retrigger cypress-rest

**Comment by satyam-harness** [comment]
retrigger cypress-cv

**Review by pankajsingh-harness — APPROVED** [review]

**Comment by satyam-harness** [comment]
retrigger jest

**Comment by satyam-harness** [comment]
retrigger prettier

**Comment by satyam-harness** [comment]
retrigger eslint

**Comment by satyam-harness** [comment]
retrigger typecheck

**Comment by satyam-harness** [comment]
retrigger sonar

**Comment by satyam-harness** [comment]
retrigger typecheck

**Comment by satyam-harness** [comment]
retrigger titlecheck

**Comment by satyam-harness** [comment]
retrigger cypress-cv

**Comment by satyam-harness** [comment]
retrigger cypress-rest

**Comment by satyam-harness** [comment]
retrigger cypress-pipeline

**Comment by satyam-harness** [comment]
retrigger cypress-cd

**Comment by satyam-harness** [comment]
retrigger typecheck

**Comment by satyam-harness** [comment]
retrigger typecheck

**Pull request merged**
