### PR TITLE
feat: [CVS-9224]: srm ux upgrade

### PR DESCRIPTION
**Pull request by harshilbits**
##### Summary:
1. Srm ux upgrade

##### Jira Links:
1. https://harness.atlassian.net/browse/CVS-9224

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by harshilbits** [comment]
retrigger jest

**Comment by harshilbits** [comment]
trigger cypress

**Review by praneshg239 — APPROVED** [review]

**Comment by harshilbits** [comment]
trigger cypress

**Comment by harshilbits** [comment]
retrigger jest

**Comment by harshilbits** [comment]
retrigger coverage

**Comment by harshilbits** [comment]
trigger cypress

**Pull request merged**
