### PR TITLE
fix: [CDS-52873]: do not allow runtime input for trafficPercent field

### PR DESCRIPTION
**Pull request by chetanvekariya-harness**
### Summary
- BE does not accept this field as Runtime input ("<+input>"). String is not acceptable at all. So, removing support of being marked as Runtime input.
- Go to second step of manifest and artifact when there is only one type to choose from.
- Allow multiple addition of artifact sources which was prevent earlier

#### Screenshots
Screenshot 2023-02-02 at 9 31 22 PM

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by chetanvekariya-harness** [comment]
retrigger coverage

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Comment by chetanvekariya-harness** [comment]
retry coverage

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Review by satyam-harness — DISMISSED** [review]

**Review by vkbansal-harness — APPROVED** [review]

**Review by YounixIO — APPROVED** [review]

**Pull request merged**
