### PR TITLE
fix: [BG-30]: pipeline context type error fixed

### PR DESCRIPTION
**Pull request by satyam-harness**
##### Jira Links:
https://harness.atlassian.net/browse/BG-30

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by satyam-harness** [comment]
retrigger coverage

**Comment by satyam-harness** [comment]
retrigger coverage

**Comment by satyam-harness** [comment]
trigger rebase

**Comment by satyam-harness** [comment]
retrigger jest

**Comment by satyam-harness** [comment]
trigger rebase

**Review by ishantmehtaharness — DISMISSED** [review]
LGTM

**Review by ishantmehtaharness — APPROVED** [review]
Looks Good

**Review by devinder-harness — APPROVED** [review]

**Pull request closed without merging**
