### PR TITLE
fix:[PIE-4611]:skip test

### PR DESCRIPTION
**Pull request by namanharness**
### Summary
Re-written tests using using `NG_SVC_ENV_REDESIGN`.
[PIE-4611](https://harness.atlassian.net/browse/PIE-4611)
[PIE-4608](https://harness.atlassian.net/browse/PIE-4608)

#### Screenshots

https://user-images.githubusercontent.com/110456765/196991736-d27e5d63-edd4-4a8d-9ab1-780b7ed58515.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by namanharness** [comment]
retrigger jest

**Comment by namanharness** [comment]
retrigger jest
retrigger titlecheck

**Comment by namanharness** [comment]
retrigger titlecheck

**Comment by namanharness** [comment]
retrigger jest

**Review by vkbansal-harness — APPROVED** [review]

**Review by chetanvekariya-harness — APPROVED** [review]

**Pull request merged**
