### PR TITLE
feat: [CDS-44067]: use new serverless lambda deploy step icon

### PR DESCRIPTION
**Pull request by chetanvekariya-harness**
### Summary
- use new serverless lambda deploy step icon
- Display free text field for bucketName if any of the parent fields is not of type FIXED

### JIRAs
https://harness.atlassian.net/browse/CDS-44128
https://harness.atlassian.net/browse/CDS-44067

#### Screenshots
Screenshot 2022-10-05 at 5 32 00 PM
Screenshot 2022-10-05 at 5 30 47 PM

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11656)

**Review by ishantmehtaharness — APPROVED** [review]
Looks Good

**Comment by chetanvekariya-harness** [comment]
retrigger titlecheck

**Comment by chetanvekariya-harness** [comment]
trigger cypress

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
