### PR TITLE
feat: [OPA-873]: passing git components into OPA MFE

### PR DESCRIPTION
**Pull request by kylekstewart**
### Summary

Passing GitX hooks/components into OPA MFE

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by bgribben-harness — APPROVED** [review]

**Review by stuart-mcdonnell — APPROVED** [review]

**Comment by kylekstewart** [comment]
retrigger titlecheck, retrigger cypress-cd, retrigger cypress-pipeline, retrigger jest

**Comment by kylekstewart** [comment]
retrigger jest

**Comment by kylekstewart** [comment]
retrigger cypress-cd

**Comment by kylekstewart** [comment]
retrigger titlecheck

**Comment by kylekstewart** [comment]
retrigger cypress-pipeline

**Pull request merged**
