### PR TITLE
fix: [CDS-80659]: making artifactPaths list empty whena artifactPaths api call fails in generic artifactory

### PR DESCRIPTION
**Pull request by satyam-harness**
### Summary
Bug - When a correct directory is provided for Artifactory Generic artifact and Artifact Paths are fetched, if the directory is updated with incorrect value and get call for Artifact Paths fails UI still shows older list.

Solution - Currently we were not emptying the list of artifact when any error occures . Updated that condition to clear the field when error has occured.

Manual Test - 

- Tested behaviour when API fails, list is getting cleared.
- Tested behaviour when API passes and has no items, list is empty in this case.

#### Screenshots

Before - 

https://github.com/harness/harness-core-ui/assets/96036463/b8d15916-85e3-4b69-94d0-84fce7790492

https://github.com/harness/harness-core-ui/assets/96036463/7421a16e-c1b8-4a97-a4a5-4483eab19300

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

### CODE REVIEW

**Comment by satyam-harness** [comment]
retrigger jest

**Comment by satyam-harness** [comment]
retrigger coverage

**Comment by satyam-harness** [comment]
retrigger standards

**Comment by satyam-harness** [comment]
retrigger eslint

**Comment by satyam-harness** [comment]
retrigger coverage

**Comment by satyam-harness** [comment]
retrigger prettier

**Comment by satyam-harness** [comment]
retrigger eslint

**Review by Eric761 — APPROVED** [review]

**Review by samarth-sharma31 — APPROVED** [review]

**Pull request merged**
