### PR TITLE
fix: [PIE-2342]: Adding cypress E2E tests for pipeline flows

### PR DESCRIPTION
**Pull request by samarth-sharma31**
##### Summary:

Adds cypress coverage for E2E tests in the following areas --->

1. Confirm without saving dialog
2. Delete pipeline stage
3. Visual to YAML parity of deploy stage form
4. Visual to variable view parity of deploy stage form
5. Pipeline notifications flow

##### Jira Links:
Ticket for tracking -> https://harness.atlassian.net/browse/PIE-2342
Epic link -> https://harness.atlassian.net/browse/PIE-2298
Doc containing cypress tests ---> https://docs.google.com/spreadsheets/d/1ufD31ruBClPSpP0pcUgD3fhg0dN5aBGRSTX3GaNFrs0/edit#gid=0

##### Screenshots:

Screenshot 2022-01-25 at 3 46 51 AM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by samarth-sharma31** [comment]
retrigger typecheck

**Comment by samarth-sharma31** [comment]
retrigger jest

**Review by kapilkumawat86 — APPROVED** [review]

**Review by chiragp1212 — DISMISSED** [review]

**Comment by samarth-sharma31** [comment]
trigger cypress

**Comment by samarth-sharma31** [comment]
trigger cypress

**Review by chetanvekariya-harness — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Review by chiragp1212 — APPROVED** [review]

**Pull request merged**
