### PR TITLE
fix: [CDS-85862]: Refactors logic to make infrastructure input independent of Env when it is configured as runtime

### PR DESCRIPTION
**Pull request by samarth-sharma31**
### Summary

Issue -> Infrastructure field getting automatically set as runtime input when custom stage template is being used in pipeline chaining and it’s value is kept empty (since it is optional for custom stage). It is happening because we are using merge template inputs call and “infrastructureDefinitions” is set as <+input> in the template because when a custom stage template is created - infrastructureDefinitions is being set as runtime input along with environmentRef field,  which is consistent with deploy stage and works fine there since infra is mandatory.

This behaviour needs to be updated for custom stage as env and infra are optional here and so they need to be configured separately. 

So going forward, the custom stage behaviour for Env Infra will be as follows ->

When env is set as runtime - we will only mark environmentRef field as runtime, visual view will show infrastructureDefinitions as empty (similar to when env is fixed/ expression and non empty). This will allow users to use only env and will not show infra input when it is not required.

#### Screenshots

Before fix --->

https://github.com/harness/harness-core-ui/assets/96409598/69233a31-c1a9-418b-9209-bfe132ba7a4e

After fix --> 

**customer stage template sanity ->**

https://github.com/harness/harness-core-ui/assets/96409598/18ad53a2-fb39-41f0-b894-b43b6c0845f8

**Customer use case - using only env in custom stage chained pipeline -->**

https://github.com/harness/harness-core-ui/assets/96409598/5f11a785-ec1c-4da9-9767-19b4b7b85050

**Using both env and infra in custom stage chained pipeline -->**

https://github.com/harness/harness-core-ui/assets/96409598/673a36ae-2281-4ac3-8712-9bd8a39a6c65

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

### CODE REVIEW

**Comment by samarth-sharma31** [comment]
trigger messagecheck

**Comment by samarth-sharma31** [comment]
trigger messagecheck

**Comment by samarth-sharma31** [comment]
Coverage check is failing due to existing files -> Ticket for tracking -> https://harness.atlassian.net/browse/CDS-77492

Coverage for new code has already been added.

**Review by chetanvekariya-harness — APPROVED** [review]

**Review by ishantmehtaharness — APPROVED** [review]
Lioks good to me

**Review by sunnykesh-harness — APPROVED** [review]

**Pull request merged**
