### PR TITLE
feat: [CDS-41164]: Removed FF--TF_MODULE_SOURCE_INHERIT_SSH

### PR DESCRIPTION
**Pull request by sonaligoyal-harness**
#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by sonaligoyal-harness** [comment]
retrigger titlecheck

**Review by chetanvekariya-harness — APPROVED** [review]

**Review by PratyushGar — DISMISSED** [review]

**Review by satyam-harness — DISMISSED** [review]

**Comment by sonaligoyal-harness** [comment]
dockerize

**Review by satyam-harness — APPROVED** [review]

**Review by PratyushGar — APPROVED** [review]

**Comment by sonaligoyal-harness** [comment]
retrigger jest

**Comment by sonaligoyal-harness** [comment]
retrigger build

**Pull request merged**
