### PR TITLE
fix: [CHAOS-318]: changed terminologies, fixed delegate and default setting routing issue

### PR DESCRIPTION
**Pull request by SahilKr24**
Signed-off-by: Sahil <sahil@harness.io>

### Summary

Added missing routes in `RouteDestinations` in `75-chaos` module to fix routing issue for Delegates and Default Settings NavLink under Project Setup Menu for Chaos Module

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 5 Issues 
* Code issue 5 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11512)

**Comment by SahilKr24** [comment]
trigger cypress

**Review by arkajyotiMukherjee — DISMISSED** [review]

**Review by hrishavjha — DISMISSED** [review]

**Review by abhinavrastogi-harness — DISMISSED** [review]

**Comment by SahilKr24** [comment]
retrigger jest

**Comment by SahilKr24** [comment]
retrigger coverage

**Comment by SahilKr24** [comment]
trigger cypress

**Review by abhinavrastogi-harness — APPROVED** [review]

**Review by S-ayanide — APPROVED** [review]

**Pull request merged**
