### PR TITLE
fix: [GTM-730]: fix handle licenses null check

### PR DESCRIPTION
**Pull request by nanaxuHarness**
##### Summary:

this is the hotfix to https://harness.atlassian.net/browse/PLG-730

##### Jira Links:

https://harness.atlassian.net/browse/PLG-730

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Review by kapilkumawat86 — DISMISSED** [review]

**Review by abhinavrastogi-harness — DISMISSED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Comment by nanaxuHarness** [comment]
retrigger jest

**Comment by nanaxuHarness** [comment]
trigger cypress

**Comment by nanaxuHarness** [comment]
retrigger coverage

**Comment by nanaxuHarness** [comment]
retrigger jest

**Review by abhinavrastogi-harness — APPROVED** [review]

**Pull request merged**
