### PR TITLE
fix: [PL-43925]: Prevent MultiSelect reset-to-top

### PR DESCRIPTION
**Pull request by mayankVermaHarness**
### Summary

JIRA: https://harness.atlassian.net/browse/PL-43925
Prevent MultiSelect reset-to-top.
Upgraded UI-Core version, which internally fixed this in MultiSelect component.

Corresponding UICore PR: https://github.com/harness/uicore/pull/1222

#### Screenshots

BEFORE:

https://github.com/harness/harness-core-ui/assets/96057095/cd7e6dbe-f873-49ae-a485-93d052e29c66

AFTER:

https://github.com/harness/harness-core-ui/assets/96057095/3fa55cd3-f55d-45f4-8397-92961c53e2cb

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

### CODE REVIEW

**Comment by mayankVermaHarness** [comment]
trigger messagecheck

**Review by namanharness — DISMISSED** [review]

**Review by PratyushGar — APPROVED** [review]

**Review by knagurski — APPROVED** [review]
👍🏻

**Review by namanharness — APPROVED** [review]

**Review by jenil-harness — APPROVED** [review]
LGTM

**Review by bhavya-sinha — APPROVED** [review]
LGTM

**Pull request merged**
