### PR TITLE
fix: [PIE-2609]: triggeredBy name in single line

### PR DESCRIPTION
**Pull request by Sagar-Rajput7**
##### Summary:

Fixed the CSS - triggered by name now in a single line

##### Jira Links:

https://harness.atlassian.net/browse/PIE-2609

##### Screenshots:

image

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by Sagar-Rajput7** [comment]
retrigger titlecheck

**Review by yc147 — APPROVED** [review]

**Review by bhavya-sinha — DISMISSED** [review]

**Comment by Sagar-Rajput7** [comment]
trigger rebase

**Comment by Sagar-Rajput7** [comment]
trigger cypress

**Review by yc147 — APPROVED** [review]

**Review by ishantmehtaharness — APPROVED** [review]
Looks Good Sagar

**Pull request merged**
