### PR TITLE
feat: [CDS-48618]:fs-fix

### PR DESCRIPTION
**Pull request by litvinovstas**
### Summary
Fix for selecting file store value,
Fix for open file store popup from path link in manifests/config files
Screenshot 2023-01-18 at 17 44 37

Screenshot 2023-01-18 at 17 42 54

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by litvinovstas** [comment]
retrigger jest

**Comment by litvinovstas** [comment]
retrigger cypress-rest

**Comment by litvinovstas** [comment]
retrigger cypress-rest

**Comment by YounixM** [comment]
Approved develop PR - https://github.com/harness/harness-core-ui/pull/13545

**Comment by YounixIO** [comment]
Approved develop PR - https://github.com/harness/harness-core-ui/pull/13560

**Review by vikrant-harness — APPROVED** [review]

**Comment by YounixIO** [comment]
retrigger cypress-rest

**Comment by YounixIO** [comment]
retrigger cypress-cd

**Review by YounixIO — DISMISSED** [review]

**Review by Sagar-Rajput7 — DISMISSED** [review]

**Review by YounixM — APPROVED** [review]

**Review by vikrant-harness — APPROVED** [review]

**Review by YounixIO — APPROVED** [review]

**Review by PratyushGar — APPROVED** [review]

**Review by chetanvekariya-harness — DISMISSED** [review]

**Review by PratyushGar — APPROVED** [review]

**Review by satyam-harness — APPROVED** [review]

**Comment by litvinovstas** [comment]
retrigger coverage

**Comment by YounixIO** [comment]
retrigger cypress-rest

**Comment by YounixIO** [comment]
retrigger cypress-cd

**Comment by YounixIO** [comment]
retrigger cypress-cv

**Comment by YounixIO** [comment]
retrigger cypress-pipeline

**Comment by YounixIO** [comment]
retrigger cypress-rest

**Review by YounixIO — APPROVED** [review]

**Comment by litvinovstas** [comment]
retrigger cypress-cv

**Pull request merged**
