### PR TITLE
fix: [CDS-85964]: Added considering whitespaces as diff, by default in MonaccoDiffEditor

### PR DESCRIPTION
**Pull request by Sagar-Rajput7**
### Summary

- Added considering whitespaces as diff, by default in MonaccoDiffEditor
- Also, removed ignore whitespace diff from the few existing diff editor occurrences such as audit trail and reconcile, as it doesn't make sense to have, caused any indentation or any whitespace diff. won't be captured.

Testing: 
- Manually tested the MonaccoDiffEditor occurrence such as -
   - Reconcile diff
   - Git diff
   - Audit trail diff

#### Screenshots

| Before | After |
|:-:|---|
| Screenshot 2023-12-07 at 12 48 34 AM | Screenshot 2023-12-07 at 12 47 02 AM |
| Screenshot 2023-12-07 at 12 49 50 AM | Screenshot 2023-12-07 at 12 49 10 AM |
| Screenshot 2023-12-07 at 12 59 04 AM | Screenshot 2023-12-07 at 12 58 46 AM |

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
- MessageMetadata: `trigger messagecheck`
- GitLeaks: `trigger gitLeaks`
</details>

## PR check failures and solutions
https://harness.atlassian.net/wiki/spaces/BT/pages/21106884744/PR+Checks+-+Failures+and+Solutions

### Rebase Instructions:
To rebase your branch onto the latest changes in the target branch, simply use the following command in a comment: `/rebase`

### CODE REVIEW

**Comment by Sagar-Rajput7** [comment]
trigger messagecheck

**Comment by Sagar-Rajput7** [comment]
trigger messagecheck

**Review by vikrant-harness — APPROVED** [review]

**Review by satyam-harness — APPROVED** [review]

**Review by namanharness — APPROVED** [review]

**Comment by Sagar-Rajput7** [comment]
coverage check failing due to low coverage % for existing files
image

**Comment by pankajsingh-harness** [comment]
@Sagar-Rajput7 I think 1st one is a valid use-case. To show empty lines for the deleted lines.

**Comment by Sagar-Rajput7** [comment]
> @Sagar-Rajput7 I think 1st one is a valid use-case. To show empty lines for the deleted lines.

sure will check if monacco supports something for this

**Comment by Sagar-Rajput7** [comment]
Coverage ticket - https://harness.atlassian.net/browse/CDS-86396

**Pull request merged**
