### PR TITLE
fix: [PIE-4790] : Fixed "What would you like to deploy?" broken UI issue on High resolution

### PR DESCRIPTION
**Pull request by pankajsingh-harness**
### Summary
This issue was happening due to the Card Component as the Card component has display "inline-block". So on the large screen, two cards come side by side. 
Wrapped the Card Component inside div to fix this issue.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by bhavya-sinha — DISMISSED** [review]

**Comment by vkbansal-harness** [comment]
retrigger titlecheck

**Review by udayvunnam — DISMISSED** [review]

**Comment by pankajsingh-harness** [comment]
retrigger titlecheck

**Comment by pankajsingh-harness** [comment]
retrigger typecheck

**Comment by bhavya-sinha** [comment]
retrigger titlecheck

**Review by bhavya-sinha — APPROVED** [review]

**Review by vkbansal-harness — APPROVED** [review]

**Pull request merged**
