### PR TITLE
fix: [PIE-3349]: Validate input set after it is applied

### PR DESCRIPTION
**Pull request by depanshu-dhiman**
##### Summary:
In PIE-3349, the Run button remained disabled ever after a valid input set was applied and all fields were not invalid.
To resolve this, run the validation function after the input set is applied. This will set the `formErrors` to the correct state.

##### Jira Links:
https://harness.atlassian.net/browse/PIE-3349

##### Screenshots:
Step 1

Screenshot 2022-04-01 at 6 53 24 PM

Step 2

Screenshot 2022-04-01 at 6 53 35 PM

Step 3

Screenshot 2022-04-01 at 6 53 54 PM

Step 4 - Result

Screenshot 2022-04-01 at 6 54 04 PM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Review by kapilkumawat86 — DISMISSED** [review]

**Review by AshwinBhatkal-Harness — DISMISSED** [review]

**Comment by depanshu-dhiman** [comment]
trigger cypress

**Comment by depanshu-dhiman** [comment]
retrigger cypress

**Comment by depanshu-dhiman** [comment]
trigger cypress

**Comment by depanshu-dhiman** [comment]
trigger cypress

**Comment by depanshu-dhiman** [comment]
trigger cypress

**Comment by depanshu-dhiman** [comment]
trigger cypress

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
