### PR TITLE
feat: [CDS-46582]: Add gitops disaster recovery feature flag

### PR DESCRIPTION
**Pull request by GeorgiosP**
### Summary

Add feature flag enum value for Disaster recovery for Gitops, 
we will be consuming this from the`AppStoreContext` 

additional context can be found here: https://harness.slack.com/archives/C01KV1X9BBR/p1669049380252239?thread_ts=1669049122.350359&cid=C01KV1X9BBR 

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by knagurski — DISMISSED** [review]
Looks good

**Comment by GeorgiosP** [comment]
I'm seeing some failing tests that are not related here not sure why maybe the snapshots have not been updated @ishantmehtaharness  do you know why this might be happening?

**Review by cjlee01 — DISMISSED** [review]

**Review by ishantmehtaharness — APPROVED** [review]
Looks good

**Review by ishantmehtaharness — APPROVED** [review]
Looks Good

**Review by knagurski — APPROVED** [review]
👍

**Pull request merged**
