### PR TITLE
fix: [CDS-59309]: Fix move to git issue for legacy DB template 

### PR DESCRIPTION
**Pull request by litvinovstas**
### Summary
Fixed issue with move to remote for legacy templates

Tested the changes with E2E with @utkarshchoubey-harness  :
1. We simulated legacy template by removing storeType to one of Inline template
2. Then, verified Move to Git is working as expected

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by litvinovstas** [comment]
retrigger titlecheck

**Comment by litvinovstas** [comment]
retrigger cypress-cd

**Comment by litvinovstas** [comment]
retrigger cypress-pipeline

**Comment by litvinovstas** [comment]
retrigger cypress-cv

**Review by samarth-sharma31 — APPROVED** [review]

**Review by AshwinBhatkal-Harness — DISMISSED** [review]

**Comment by litvinovstas** [comment]
retrigger cypress-cv

**Review by sunnykesh-harness — APPROVED** [review]

**Comment by litvinovstas** [comment]
retrigger cypress-cd

**Comment by litvinovstas** [comment]
retrigger jest

**Review by samarth-sharma31 — APPROVED** [review]

**Comment by litvinovstas** [comment]
retrigger cypress-pipeline

**Comment by litvinovstas** [comment]
retrigger jest

**Review by utkarshchoubey-harness — APPROVED** [review]

**Pull request merged**
