### PR TITLE
chore: [CDS-35448]: add test cases for ServerlessAwsLambdaServiceSpec

### PR DESCRIPTION
**Pull request by chetanvekariya-harness**
##### Jira Links:
https://harness.atlassian.net/browse/CDS-35448

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Comment by chetanvekariya-harness** [comment]
retrigger coverage

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Comment by chetanvekariya-harness** [comment]
retrigger coverage

**Comment by chetanvekariya-harness** [comment]
dockerize

**Review by devinder-harness — APPROVED** [review]

**Pull request merged**
