### PR TITLE
fix: [PL-28510]: Disable save button in pipeline/template studio on intermittent loading

### PR DESCRIPTION
**Pull request by depanshu-dhiman**
### Summary
If a pipeline/template is using a template, there is a delay in API response because API needs to resolve the nested dependencies, meaning - If Template A uses Template B and B uses C, and so on... it will take a long time to resolve the template fully. While the API is in progress, right now we allow the user to click on "Save" button which will result is Save API throwing an exception.

To solve this, we have introduced a new boolean state in pipeline and template context - `isIntermittentLoading`
This state variable can be used for any logic and let the components know that something is going on.

In this PR, we introduce this new state variable and use this state variable to disable the Save buttons.

Affects Pipeline Studio's and Template Studio's "Save" , "Save as Template", "Apply Changes", "Save as new version", "Save as new Template" buttons.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 No issues Everything looks good
 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11503)

**Comment by depanshu-dhiman** [comment]
retrigger titlecheck

**Comment by depanshu-dhiman** [comment]
retrigger jest

**Comment by depanshu-dhiman** [comment]
retrigger jest

**Comment by depanshu-dhiman** [comment]
retrigger jest

**Comment by depanshu-dhiman** [comment]
trigger cypress

**Review by yc147 — APPROVED** [review]

**Pull request merged**
