### PR TITLE
fix: [PIE-3282]: Fixed flaky test

### PR DESCRIPTION
**Pull request by goyalsonali**
Summary:

Fixed flaky test

Jira Links:

Screenshots:
You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by goyalsonali** [comment]
retrigger titlecheck

**Comment by goyalsonali** [comment]
trigger cypress

**Comment by goyalsonali** [comment]
retrigger eslint

**Comment by goyalsonali** [comment]
trigger cypress

**Review by bhavya-sinha — APPROVED** [review]

**Pull request merged**
