### PR TITLE
fix: [CDS-35227]: using newly added field for resolved yaml in get pi…

### PR DESCRIPTION
**Pull request by samarth-sharma31**
…peline call

##### Summary:

Using newly added "resolvedTemplatesPipelineYaml" from get pipeline api instead of "template/api/templates/applyTemplates? " at -

RunPipelineForm, InputSetForm and Retry Pipeline

##### Jira Links:

https://harness.atlassian.net/browse/CDS-35227

##### Screenshots:

https://user-images.githubusercontent.com/96409598/159364931-d76f47b4-83f0-4a8c-b6fc-53dab6891a0d.mov

https://harness.atlassian.net/browse/CI-3802

**Trigger functionality testing -->** 

https://user-images.githubusercontent.com/96409598/161148517-f95e85a3-182b-4444-b9b9-eb86ac3ff9fc.mov

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by samarth-sharma31** [comment]
trigger cypress

**Comment by samarth-sharma31** [comment]
retrigger jest

**Comment by samarth-sharma31** [comment]
retrigger jest

**Comment by samarth-sharma31** [comment]
trigger cypress

**Review by yc147 — DISMISSED** [review]

**Comment by AshwinBhatkal-Harness** [comment]
dockerize

**Comment by samarth-sharma31** [comment]
dockerize

**Comment by samarth-sharma31** [comment]
retrigger jest

**Comment by samarth-sharma31** [comment]
dockerize

**Review by vardanbansal-harness — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
