### PR TITLE
fix: [CDS-34571]: on service row select, service details page should appear

### PR DESCRIPTION
**Pull request by chetanvekariya-harness**
##### Summary:
- Do not extract identifier before checking if object is present
- Pass correct data to prop function on selection of row
- Fix test cases by mocking data properly

##### Jira Links:
https://harness.atlassian.net/browse/CDS-34571

##### Screenshots:
Screenshot 2022-03-04 at 5 02 48 PM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by chetanvekariya-harness** [comment]
retrigger coverage

**Review by kapilkumawat86 — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]
Lgtm

**Comment by chetanvekariya-harness** [comment]
trigger cypress

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Review by kapilkumawat86 — APPROVED** [review]

**Review by ishantmehtaharness — APPROVED** [review]
Approved

**Review by yc147 — APPROVED** [review]

**Comment by chetanvekariya-harness** [comment]
retrigger standards

**Pull request merged**
