### PR TITLE
fix: [PIE-2742]: Corrected the overflow

### PR DESCRIPTION
**Pull request by Sagar-Rajput7**
##### Summary:

Problem:
- Lagre InputSet names were overflowing
- Also checked check box was not visible earlier due to less space

Now:
- Corrected overflow and checked checkbox is also visible

Also the Full name will be visible on hover (2nd Image)

##### Jira Links:

https://harness.atlassian.net/browse/PIE-2742

##### Screenshots:

image

image

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by Sagar-Rajput7** [comment]
trigger rebase

**Comment by Sagar-Rajput7** [comment]
retrigger jest

**Comment by Sagar-Rajput7** [comment]
trigger cypress

**Review by ishantmehtaharness — APPROVED** [review]
Looks good now

**Review by yc147 — APPROVED** [review]

**Pull request merged**
