### PR TITLE
feat: [CDS-47127]: force delete template

### PR DESCRIPTION
**Pull request by RajBaviskar**
### Summary

- Force delete for Template 

#### Screenshots
Screen Shot 2023-01-15 at 8 53 27 PM

https://user-images.githubusercontent.com/7086440/212828845-475ced79-7fc0-4554-93fc-23541fdb8c99.mov

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by RajBaviskar** [comment]
trigger Title_Check

**Comment by RajBaviskar** [comment]
trigger title_check

**Comment by RajBaviskar** [comment]
retrigger titlecheck

**Comment by RajBaviskar** [comment]
retrigger cypress-rest

**Comment by RajBaviskar** [comment]
retrigger cypress-cv

**Comment by RajBaviskar** [comment]
retrigger cypress-rest

**Comment by RajBaviskar** [comment]
retrigger cypress-cv

**Comment by RajBaviskar** [comment]
retrigger cypress-rest

**Comment by RajBaviskar** [comment]
retrigger cypress-cv

**Comment by RajBaviskar** [comment]
retrigger jest

**Comment by RajBaviskar** [comment]
retrigger cypress-cd

**Review by AshwinBhatkal-Harness — APPROVED** [review]

**Comment by RajBaviskar** [comment]
retrigger cypress-cd

**Comment by RajBaviskar** [comment]
retrigger cypress-cd

**Comment by RajBaviskar** [comment]
retrigger cypress-cd

**Comment by praneshg239** [comment]
And please add swagger in the PR which is causing the services change, so that the swagger and services index file will be in sync.

**Review by vkbansal-harness — APPROVED** [review]

**Pull request merged**
