### PR TITLE
fix: [cds-43179]: clear tags on change dependant fields

### PR DESCRIPTION
**Pull request by azharness**
#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by azharness** [comment]
retrigger coverage

**Comment by azharness** [comment]
retrigger jest

**Review by vikrant-harness — APPROVED** [review]

**Review by Sagar-Rajput7 — APPROVED** [review]

**Review by vikrant-harness — APPROVED** [review]

**Review by Sagar-Rajput7 — APPROVED** [review]

**Comment by azharness** [comment]
trigger cypress

**Comment by azharness** [comment]
trigger cypress

**Comment by azharness** [comment]
trigger rebase

**Comment by azharness** [comment]
trigger cypress

**Comment by azharness** [comment]
retrigger typecheck

**Comment by azharness** [comment]
trigger cypress

**Comment by azharness** [comment]
retrigger typecheck

**Comment by azharness** [comment]
retrigger titlecheck

**Comment by azharness** [comment]
retrigger typecheck

**Comment by azharness** [comment]
trigger cypress

**Pull request merged**
