### PR TITLE
feat: [PL-31389]: removed FF usage for PL_REMOVE_EXTERNAL_USER_ORG_PROJECT

### PR DESCRIPTION
**Pull request by tiwaritejas**
### Summary

Since the FF- PL_REMOVE_EXTERNAL_USER_ORG_PROJECT has been globally enabled, this PR cleans up its usages from code.
Testing:
No specific testing required. Just the functionality to delete externally managed users from orgs and projects should continue to work as expected.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by tiwaritejas** [comment]
retrigger messagecheck

**Comment by tiwaritejas** [comment]
retrigger titlecheck

**Review by mayankVermaHarness — DISMISSED** [review]

**Review by avinashmadhwani02 — APPROVED** [review]

**Review by mayankVermaHarness — APPROVED** [review]

**Comment by tiwaritejas** [comment]
retrigger cypress-pipeline

**Comment by tiwaritejas** [comment]
retrigger cypress-pipeline

**Review by pbarapatre10 — APPROVED** [review]

**Review by mayankVermaHarness — APPROVED** [review]

**Review by avinashmadhwani02 — APPROVED** [review]

**Pull request merged**
