### PR TITLE
fix: [CDS-34863]: add vertical scroll, change button size, don't wrap button

### PR DESCRIPTION
**Pull request by Tamaraius**
##### Jira Links:
https://harness.atlassian.net/browse/CDS-34863

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by Tamaraius** [comment]
retrigger jest

**Comment by Tamaraius** [comment]
retrigger coverage

**Comment by Tamaraius** [comment]
retrigger jest

**Comment by Tamaraius** [comment]
retrigger coverage

**Comment by Tamaraius** [comment]
retrigger coverage

**Review by bhavya-sinha — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
