### PR TITLE
fix: [PIE-3711]: Fixed active color

### PR DESCRIPTION
**Pull request by ishantmehtaharness**
##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

Jira: https://harness.atlassian.net/browse/PIE-3711

### CODE REVIEW

**Comment by ishantmehtaharness** [comment]
retrigger titlecheck

**Review by kapilkumawat86 — APPROVED** [review]

**Review by udayvunnam — APPROVED** [review]

**Comment by ishantmehtaharness** [comment]
retrigger titlecheck

**Comment by ishantmehtaharness** [comment]
retrigger coverage

**Comment by ishantmehtaharness** [comment]
Coverage is failing because of this

-----------------------|---------|----------|---------|---------|-------------------
File                   | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
-----------------------|---------|----------|---------|---------|-------------------
All files              |      25 |        0 |       0 |   25.35 |                   
 PipelineStageNode.tsx |      25 |        0 |       0 |   25.35 | 47-278            
-----------------------|---------|----------|---------|---------|-------------------

**Review by devinder-harness — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Review by AshwinBhatkal-Harness — APPROVED** [review]

**Pull request merged**
