### PR TITLE
fix: [PLG-1542]: correct values fix for workloads based on licenseType

### PR DESCRIPTION
**Pull request by dhruvUpadhyay07**
#### Screenshots

NA

#### PR Checklist

<details>
Screenshot 2022-10-18 at 9 46 10 PM

<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by dhruvUpadhyay07** [comment]
retrigger titlecheck

**Comment by dhruvUpadhyay07** [comment]
trigger cypress

**Review by devinder-harness — APPROVED** [review]

**Review by sonaligoyal-harness — APPROVED** [review]

**Review by pranil-harness — APPROVED** [review]

**Comment by dhruvUpadhyay07** [comment]
trigger cypress

**Comment by dhruvUpadhyay07** [comment]
trigger cypress

**Comment by dhruvUpadhyay07** [comment]
trigger cypress

**Comment by dhruvUpadhyay07** [comment]
trigger cypress

**Review by pranil-harness — APPROVED** [review]

**Pull request merged**
