### PR TITLE
feat: [SRM-14003]: add SRM_ET_JIRA_INTEGRATION FF for code errors MFE

### PR DESCRIPTION
**Pull request by guycastel**
### Summary
Add `SRM_ET_JIRA_INTEGRATION` feature flag to use in error tracking / code errors MFE (that's what the `microfrontends` package version bump is for).

[Corresponding harness-core PR](https://github.com/harness/harness-core/pull/44115)

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by knagurski — DISMISSED** [review]
👍🏻

**Review by abhinavrastogi-harness — DISMISSED** [review]

**Review by David-Kreiner — DISMISSED** [review]

**Comment by guycastel** [comment]
retrigger jest

**Comment by guycastel** [comment]
retrigger coverage

**Comment by guycastel** [comment]
retrigger jest

**Review by David-Kreiner — DISMISSED** [review]

**Review by knagurski — DISMISSED** [review]

**Review by ricksjames — DISMISSED** [review]

**Review by cseverino789 — DISMISSED** [review]

**Review by David-Kreiner — APPROVED** [review]

**Review by knagurski — APPROVED** [review]

**Pull request merged**
