### PR TITLE
feat: [PIE-3541]: Type issue in UserInfo

### PR DESCRIPTION
**Pull request by reetika04**
##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by reetika04** [comment]
retrigger jest

**Comment by reetika04** [comment]
etrigger jest

**Comment by reetika04** [comment]
retrigger jest

**Review by bhavya-sinha — APPROVED** [review]

**Review by jenil-harness — APPROVED** [review]
LGTM for ce

**Review by nanaxuHarness — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
