### PR TITLE
fix:[CI-6904]: error logs expand full width if issueCouldBe or tryTheseSuggesions is unavailable

### PR DESCRIPTION
**Pull request by shaurya-harness**
### Summary

error logs will expand full width if issueCouldBe or tryTheseSuggestions is not available, conversely all three will divide into columns of equal space if error data is available

#### Screenshots

Screenshot 2023-02-28 at 3 27 41 PM
 and after changes where applicable-->

<!-- ✍️ Add screenshots of before

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by shaurya-harness** [comment]
retrigger cypress-cd

**Comment by shaurya-harness** [comment]
retrigger titlecheck

**Comment by shaurya-harness** [comment]
retrigger jest

**Review by d1wilko — APPROVED** [review]
LGTM

**Review by rameshx — APPROVED** [review]

**Comment by shaurya-harness** [comment]
retrigger cypress-pipeline

**Pull request merged**
