### PR TITLE
feat: [PIE-4994]: ServiceNow Import Set

### PR DESCRIPTION
**Pull request by Eric761**
### Summary

ServiceNow Import Set Step

#### Screenshots

Screenshot 2022-10-09 at 8 26 39 AM

image

image

#### Video

https://user-images.githubusercontent.com/73639897/194735952-bf313324-bc63-423b-8d25-19813bbbcee1.mov

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 174 Issues 
* Code issue 174 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11327)

**Comment by Eric761** [comment]
retrigger titlecheck

**Comment by Eric761** [comment]
retrigger coverage

**Comment by Eric761** [comment]
retrigger jest

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
