### PR TITLE
fix: [DEL-3754]: Fixed missing icons for type delegate in audit trail

### PR DESCRIPTION
**Pull request by amitsh14**
##### Summary:

Delegate resource will appear in multi-select filter and fixed missing icons for type delegate in audit trail data table

##### Jira Links:

https://harness.atlassian.net/browse/DEL-3754?atlOrigin=eyJpIjoiMDEwNDQ4YmM4OWU5NDRhYmFmMjYzNzdjMzg1NDg4ZTciLCJwIjoiaiJ9

#### Showing delegate resource in filter

Screenshot 2022-04-28 at 8 42 42 PM

#### Showing icons for type delegate

Screenshot 2022-04-28 at 8 42 58 PM

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Review by avinashmadhwani02 — APPROVED** [review]

**Comment by amitsh14** [comment]
retrigger typecheck

**Review by arpit3107 — APPROVED** [review]

**Comment by amitsh14** [comment]
trigger rebase

**Comment by amitsh14** [comment]
retrigger titlecheck

**Comment by amitsh14** [comment]
trigger cypress

**Pull request merged**
