### PR TITLE
feat: [CDS-40602]: Update command list UI

### PR DESCRIPTION
**Pull request by rameshx**
### Summary

Updates the command list UI.
Fixes an issue where elements below the list overflow with the list items while dragging.

#### Screenshots
before:
image

after:
image

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Passed_** 
 


            
 #### 2 Issues 
* Code issue 2 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/10417)

**Comment by rameshx** [comment]
retrigger titlecheck

**Review by chetanvekariya-harness — APPROVED** [review]
Edit and Delete icon size looks different.

**Comment by rameshx** [comment]
> Edit and Delete icon size looks different.

Inspected them, both SVGs have the same size (16px).

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
