### PR TITLE
Chore: [CDS-74900]: Add jest test cases for ServerlessDeploy step

### PR DESCRIPTION
**Pull request by MondalSayantan**
### Summary

Added jest test cases for Serverless AWS lambda V2 deploy step

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [x] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by chetanvekariya-harness — DISMISSED** [review]

**Comment by MondalSayantan** [comment]
retrigger cypress-cv

**Comment by MondalSayantan** [comment]
retrigger cypress-rest

**Comment by MondalSayantan** [comment]
retrigger cypress-cd

**Comment by MondalSayantan** [comment]
retrigger cypress-pipeline

**Comment by MondalSayantan** [comment]
retrigger cypress-cv

**Comment by MondalSayantan** [comment]
retrigger cypress-pipeline

**Review by sonaligoyal-harness — APPROVED** [review]

**Review by chetanvekariya-harness — APPROVED** [review]

**Pull request merged**
