### PR TITLE
feat: [CDS-38170]: add checkbox for exporting TerraformPlan as json

### PR DESCRIPTION
**Pull request by Tamaraius**
##### Summary:
add checkbox for exporting TerraformPlan as json

##### Jira Links:
https://harness.atlassian.net/browse/CDS-38170

##### Screenshots:
https://user-images.githubusercontent.com/96610348/170526617-c42913f7-3527-459b-b245-30410c9edd1d.mov

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Review by azharness — APPROVED** [review]

**Comment by Tamaraius** [comment]
retrigger coverage

**Comment by Tamaraius** [comment]
retrigger jest

**Review by azharness — APPROVED** [review]

**Comment by Tamaraius** [comment]
retrigger jest

**Review by AshwinBhatkal-Harness — DISMISSED** [review]

**Comment by Tamaraius** [comment]
retrigger coverage

**Comment by Tamaraius** [comment]
retrigger jest

**Review by azharness — DISMISSED** [review]

**Comment by Tamaraius** [comment]
retrigger coverage

**Comment by Tamaraius** [comment]
trigger rebase

**Review by AshwinBhatkal-Harness — APPROVED** [review]

**Review by AshwinBhatkal-Harness — DISMISSED** [review]

**Review by AshwinBhatkal-Harness — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
