### PR TITLE
feat: [PIE-3938]: Looping Strategy set up and execution changes

### PR DESCRIPTION
**Pull request by yc147**
##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by PratyushGar** [comment]
dockerize

**Comment by PratyushGar** [comment]
dockerize

**Comment by PratyushGar** [comment]
dockerize

**Comment by PratyushGar** [comment]
dockerize

**Comment by PratyushGar** [comment]
dockerize

**Comment by PratyushGar** [comment]
dockerize

**Review by kapilkumawat86 — DISMISSED** [review]

**Review by satyam-harness — DISMISSED** [review]

**Review by vkbansal — APPROVED** [review]

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
