### PR TITLE
fix: [CDS-46768]: allowed values changes for steps and other fixes

### PR DESCRIPTION
**Pull request by chetanvekariya-harness**
### Summary
**Other JIRAs:**
https://harness.atlassian.net/browse/PIE-6439

- Pass correct type to ConfigureOptions component for time field
- Remove two cog buttons for Repository as common component has cog button rendered

#### Screenshots
**Before:** (On QA)
- Two configure option buttons
Screenshot 2022-11-17 at 9 13 41 PM

- Select field's width issue when allowed values are configured
Screenshot 2022-11-17 at 9 11 41 PM

**After:**
Screenshot 2022-11-17 at 9 17 44 PM
Screenshot 2022-11-17 at 9 12 42 PM

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by Tamaraius — DISMISSED** [review]

**Review by AshwinBhatkal-Harness — DISMISSED** [review]

**Review by vikrant-harness — APPROVED** [review]

**Comment by chetanvekariya-harness** [comment]
retrigger cypress-cd

**Comment by chetanvekariya-harness** [comment]
retrigger cypress-pipeline

**Comment by chetanvekariya-harness** [comment]
retrigger cypress-rest

**Review by Tamaraius — APPROVED** [review]

**Comment by chetanvekariya-harness** [comment]
retrigger cypress-pipeline

**Comment by chetanvekariya-harness** [comment]
retrigger jest

**Review by kapilkumawat86 — APPROVED** [review]

**Pull request merged**
