### PR TITLE
feat: [CCM-7551]: handled disabling of fields in edit flow for GCP load balancer form

### PR DESCRIPTION
**Pull request by rishik30**
##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by rishik30** [comment]
trigger cypress

**Comment by rishik30** [comment]
trigger cypress

**Comment by rishik30** [comment]
trigger cypress

**Comment by rishik30** [comment]
trigger cypress

**Comment by rishik30** [comment]
trigger cypress

**Review by rajarshee-harness — APPROVED** [review]

**Review by jyotiarora-harness — APPROVED** [review]

**Pull request merged**
