### PR TITLE
feat: [CI-5680]: Docker infra UI work

### PR DESCRIPTION
**Pull request by d1wilko**
### Summary

Add docker infra to UI behind feature flag

#### Screenshots

image

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by diptiman-adak** [comment]
Quality gate Quality gate: **_Failed_** 
 


            
 #### 17 Issues 
* Code issue 17 Code issues 

 [Details](https://app.embold.io/organization/gh/harness/repositories/e864badd0b95ab81c060b15b85f15701/pull-request/11575)

**Comment by d1wilko** [comment]
retrigger titlecheck

**Comment by d1wilko** [comment]
trigger featurenamecheck

**Comment by d1wilko** [comment]
retrigger titlecheck

**Review by vardanbansal-harness — APPROVED** [review]

**Review by vardanbansal-harness — APPROVED** [review]

**Review by mtran7 — APPROVED** [review]

**Comment by dgarg-harness** [comment]
Force merging as this is needed for a customer committed feature to be delivered next week, we will look at the code duplication issue as a follow up.

**Pull request merged**
