### PR TITLE
fix: [CCM-7349]: anomaly notification test cases fixes

### PR DESCRIPTION
**Pull request by jyotiarora-harness**
##### Summary:

Updated flaky test cases for anomaly alerts notification

##### Jira Links:

https://harness.atlassian.net/browse/CCM-7349

##### Screenshots:

You can use the following comments to re-trigger PR Checks

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier - `fix prettier`

### CODE REVIEW

**Comment by jyotiarora-harness** [comment]
trigger cypress

**Comment by jyotiarora-harness** [comment]
trigger cypress

**Comment by jyotiarora-harness** [comment]
trigger cypress

**Comment by jyotiarora-harness** [comment]
trigger cypress

**Comment by jyotiarora-harness** [comment]
retrigger jest

**Review by rajarshee-harness — APPROVED** [review]

**Review by jenil-harness — APPROVED** [review]

**Pull request merged**
