### PR TITLE
feat: [FFM-4768]: NodeJS ReadME update

### PR DESCRIPTION
**Pull request by crystal-fong**
#### Screenshots

Updated the NodeJS getting started instructions with the ReadMe of the NodeJS SDK repo. The ReadMe has been shortened even more as the onboarding flow covers some parts of the instructions already

The Flag Name created from the UI has also been dynamically added into the code sample so users can quickly copy/paste it into their project

image
image
image
image

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress: `trigger cypress`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Review by Kira-Jennings — DISMISSED** [review]

**Comment by crystal-fong** [comment]
retrigger jest

**Review by Kira-Jennings — APPROVED** [review]

**Review by chrisblakely01 — DISMISSED** [review]

**Comment by crystal-fong** [comment]
retrigger cypress

**Comment by crystal-fong** [comment]
retrigger cypress

**Review by Kira-Jennings — APPROVED** [review]

**Comment by crystal-fong** [comment]
Retrigger cypress

**Comment by crystal-fong** [comment]
retrigger cypress

**Comment by crystal-fong** [comment]
retrigger cypress

**Comment by crystal-fong** [comment]
retrigger cypress

**Comment by crystal-fong** [comment]
retrigger cypress

**Review by chrisblakely01 — APPROVED** [review]

**Pull request merged**
