### PR TITLE
fix: [PIE-7490]: Production hot fix version update

### PR DESCRIPTION
**Pull request by pankajsingh-harness**
### Summary
This is production hot fix PR for [No Pagination on the Trigger Listing Page](https://harness.atlassian.net/browse/PIE-7490)
Cherry picked the already merged commit:[fix: \[PIE-7490\]: Added Pagination on the Trigger Listing Page]( https://github.com/harness/harness-core-ui/pull/13356) and updated the version number only.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

#### [Contributor license agreement](https://github.com/harness/harness-core-ui/blob/develop/CONTRIBUTOR_LICENSE_AGREEMENT.md)

[PIE-7490]: https://harness.atlassian.net/browse/PIE-7490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by pankajsingh-harness** [comment]
retrigger titlecheck

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Comment by pankajsingh-harness** [comment]
retrigger cypress-rest

**Comment by pankajsingh-harness** [comment]
retrigger cypress-rest

**Comment by pankajsingh-harness** [comment]
retrigger cypress-pipeline

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Comment by pankajsingh-harness** [comment]
retrigger cypress-rest

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Comment by pankajsingh-harness** [comment]
retrigger cypress-rest

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Review by Eric761 — APPROVED** [review]

**Review by PratyushGar — APPROVED** [review]

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Comment by pankajsingh-harness** [comment]
retrigger cypress-rest

**Comment by pankajsingh-harness** [comment]
retrigger cypress-rest

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Review by kapilkumawat86 — APPROVED** [review]

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Comment by pankajsingh-harness** [comment]
retrigger cypress-rest

**Comment by pankajsingh-harness** [comment]
retrigger cypress-rest

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Comment by pankajsingh-harness** [comment]
retrigger cypress-rest

**Comment by pankajsingh-harness** [comment]
retrigger cypress-rest

**Comment by pankajsingh-harness** [comment]
retrigger cypress-cd

**Pull request closed without merging**
