### PR TITLE
[feat]:[IAC-843]: Add Validate command to the plugin

### PR DESCRIPTION
**Pull request by nassergonzalez**
### Summary

Adding new command to the IACM plugin step

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by bgribben-harness** [comment]
retrigger titlecheck

**Review by bgribben-harness — APPROVED** [review]

**Review by d1wilko — APPROVED** [review]

**Comment by nassergonzalez** [comment]
retrigger cypress-rest

**Comment by nassergonzalez** [comment]
retrigger cypress-pipeline

**Comment by nassergonzalez** [comment]
retrigger cypress-cv

**Comment by nassergonzalez** [comment]
retrigger titlecheck

**Comment by nassergonzalez** [comment]
retrigger cypress-cd

**Comment by nassergonzalez** [comment]
retrigger cypress-pipeline

**Review by scottyw-harness — APPROVED** [review]

**Pull request merged**
