### PR TITLE
fix: [CDS-59458]: update how tags are sent when null on create a template filter

### PR DESCRIPTION
**Pull request by douglasnfrazao**
### Summary

When the user enters the templates page, and type only the filter name and template name (without adding anything on tags), the tags were being sent as an empty array, but it should be an empty object because that's what the backend is expecting.

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by douglasnfrazao** [comment]
retrigger titlecheck

**Comment by douglasnfrazao** [comment]
retrigger cypress-cd

**Comment by douglasnfrazao** [comment]
retrigger coverage

**Comment by douglasnfrazao** [comment]
retrigger coverage

**Comment by douglasnfrazao** [comment]
retrigger coverage

**Review by samarth-sharma31 — APPROVED** [review]

**Pull request merged**
