### PR TITLE
feat: [CI-8191]: Harness Copilot integration for CI and CD modules

### PR DESCRIPTION
**Pull request by vardanbansal-harness**
### Summary

1. This feature is to be enabled only for executions having either `CI` or `CD` module info in pipeline execution summary of a pipeline.
2. For now, all accounts in QA env will see this feature enabled. We will shortly move it behind a FF as a follow up.

image

image

image

image

image

#### Screenshots

NA

#### PR Checklist

<details>
<summary>Please check if your PR fulfils the following requirements</summary>

- [ ] Tests for the changes have been added. Ideally, include a test that fails without this PR but passes with it.
- [ ] Docs have been [added/updated](https://harness.atlassian.net/jira/software/c/projects/DOC/boards/40).
</details>

<details>
<summary>Use the following comments to re-trigger PR Checks</summary>

- Jest: `retrigger jest`
- Prettier: `retrigger prettier`
- Type Check: `retrigger typecheck`
- ESLint: `retrigger eslint`
- Sonar: `retrigger sonar`
- Standards: `retrigger standards`
- Build: `retrigger build`
- Title Check: `retrigger titlecheck`
- Feature Name Check: `trigger featurenamecheck`
- Coverage: `retrigger coverage`
- Rebase: `trigger rebase`
- Cypress Rest: `retrigger cypress-rest`
- Cypress CD: `retrigger cypress-cd`
- Cypress Pipeline: `retrigger cypress-pipeline`
- Cypress CV: `retrigger cypress-cv`
- Fix Prettier: `fix prettier`
</details>

### CODE REVIEW

**Comment by hemanthmantri** [comment]
retrigger coverage

**Comment by hemanthmantri** [comment]
retrigger cypress-rest

**Review by tan-nhu — APPROVED** [review]

**Review by ishantmehtaharness — APPROVED** [review]
Looks Good

**Review by vikrant-harness — APPROVED** [review]

**Comment by vardanbansal-harness** [comment]
Currently, code coverage for the new component is failing by a few %. Will add it positively, as a follow up PR. All other common changes have been covered.

**Comment by vardanbansal-harness** [comment]
> Currently, code coverage for the new component is failing by a few %. Will add it positively, as a follow up PR. All other common changes have been covered.

Added a ticket for tracking: https://harness.atlassian.net/browse/CI-8429

**Pull request merged**
